"""Auto-distilled motion skill: agenda_marker_sweep.

Agenda or process text enters like a marker sweep, then resolves with orderly staggered lines.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'agenda_marker_sweep'
CATEGORY = 'text'
DESCRIPTION = 'Agenda or process text enters like a marker sweep, then resolves with orderly staggered lines.'

APPLICABILITY = {
    "roles": ['agenda', 'process', 'timeline', 'list'],
    "anchor_names": ['agenda', 'bullet_list', 'steps', 'process', 'timeline'],
    "anchor_name_regex": '(?i)(agenda|bullet[_ ]?list|steps?|process|timeline)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 700}, 'sweep_duration_ms': {'default': 480, 'min': 400, 'max': 800}, 'settle_duration_ms': {'default': 520, 'min': 350, 'max': 900}, 'text_offset_ms': {'default': 90, 'min': 0, 'max': 220}, 'stagger_ms': {'default': 70, 'min': 40, 'max': 140}, 'per_duration_ms': {'default': 240, 'min': 160, 'max': 360}, 'dx_frac': {'default': 0.03, 'min': 0.0, 'max': 0.08}, 'bow_frac': {'default': -0.12, 'min': -0.22, 'max': 0.0}}

TAGS = ['agenda', 'process', 'structured', 'sweep', 'editorial']
INTENSITY = 4
EMBEDDING_TEXT = (
    'This text motion suits agendas, three-step process slides, and concise bullet groups that need more shape than a basic stagger. A lateral sweep establishes the block first, then the lines resolve in sequence with a tidy, directional rhythm. It feels like a marker stroke or editorial underline passing across the content. Best when the list is short, intentional, and layout-driven rather than dense.'
)
CONTENT_MATCHERS = {'list_like': True, 'multi_line': True, 'dense_paragraph': False}
COMPLEMENTARY_WITH = ['editorial_side_nudge', 'soft_arc_settle', 'panel_unveil_settle']
CONFLICTS_WITH = ['bullet_stagger_reveal', 'slide_in_left', 'grow_reveal']


MOOD = ['editorial', 'calm']
ARCHETYPE_FIT = ['narrative', 'research', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_arc_path, emit_text_stagger
    base_delay = int(p.get('delay_ms', 80))
    sweep_duration_ms = int(p.get('sweep_duration_ms', 480))
    settle_duration_ms = int(p.get('settle_duration_ms', 520))
    text_offset_ms = int(p.get('text_offset_ms', 90))
    stagger_ms = int(p.get('stagger_ms', 70))
    per_duration_ms = int(p.get('per_duration_ms', 240))
    dx_frac = float(p.get('dx_frac', 0.03))
    bow_frac = float(p.get('bow_frac', -0.12))
    emit_wipe_in(slide, target_shape, direction='left', delay_ms=base_delay, duration_ms=sweep_duration_ms)
    emit_arc_path(slide, target_shape, delay_ms=base_delay, duration_ms=settle_duration_ms, dx_frac=dx_frac, dy_frac=0.0, bow_frac=bow_frac)
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + text_offset_ms, stagger_ms=stagger_ms, per_duration_ms=per_duration_ms)
