"""Auto-distilled motion skill: background_parallax_glide.

Ultra-slow parallax glide for background blobs, washes, and large decorative plates.

Category: ambient. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'background_parallax_glide'
CATEGORY = 'ambient'
DESCRIPTION = 'Ultra-slow parallax glide for background blobs, washes, and large decorative plates.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'hero', 'full_bleed_image', 'backdrop'],
    "anchor_names": ['background', 'blob', 'gradient', 'wash', 'plate'],
    "anchor_name_regex": '(?i)(bg|background|blob|gradient|wash|plate|backdrop)',
    "max_per_slide": 1,
}

PARAMETERS = {'duration_ms': {'default': 9000, 'min': 5000, 'max': 10000}, 'dx_in': {'default': 0.25, 'min': -0.6, 'max': 0.6}, 'dy_in': {'default': 0.08, 'min': -0.4, 'max': 0.4}}

TAGS = ['background', 'parallax', 'cinematic', 'slow', 'decorative']
INTENSITY = 1
EMBEDDING_TEXT = (
    'This ambient treatment adds an almost imperceptible parallax glide to large background shapes such as color washes, translucent blobs, gradient plates, or decorative frames. The movement is slow and cinematic, helping a cover or hero slide feel dimensional without pulling attention away from the headline. It is especially effective on sparse layouts with oversized backdrops, abstract brand geometry, or soft image treatments. The intensity is extremely low, optimized for atmosphere and polish rather than overt motion.'
)
CONTENT_MATCHERS = {'is_background': True, 'large_shape': True, 'decorative': True, 'low_semantic_priority': True}
COMPLEMENTARY_WITH = ['hero_lens_focus', 'dramatic_zoom', 'gentle_rise_fade']
CONFLICTS_WITH = ['image_ken_burns', 'floating_card_drift', 'planet_orbit_idle']


MOOD = ['cinematic', 'calm', 'editorial', 'restrained']
ARCHETYPE_FIT = ['brand', 'narrative', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _shell_helpers import add_drift_motion
    add_drift_motion(slide, target_shape, dx_in=float(p.get('dx_in', 0.25)), dy_in=float(p.get('dy_in', 0.08)), duration_ms=int(p.get('duration_ms', 9000)), pingpong=False)
