"""Auto-distilled motion skill: badge_pinwheel_pop.

Sticker-like badge spins in from small scale for labels, icons, and playful callouts.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'badge_pinwheel_pop'
CATEGORY = 'entrance'
DESCRIPTION = 'Sticker-like badge spins in from small scale for labels, icons, and playful callouts.'

APPLICABILITY = {
    "roles": ['callout', 'badge', 'logo_lockup', 'timeline_milestone'],
    "anchor_names": ['badge', 'seal', 'icon', 'logo', 'label'],
    "anchor_name_regex": '(?i)(badge|seal|icon|logo|label)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 800}, 'duration_ms': {'default': 560, 'min': 420, 'max': 760}, 'from_pct': {'default': 72, 'min': 55, 'max': 90}, 'from_deg': {'default': 180, 'min': -270, 'max': 270}}

TAGS = ['playful', 'badge', 'sticker', 'spin', 'accent']
INTENSITY = 7
EMBEDDING_TEXT = (
    'A compact accent shape pops in with a brisk spin, like a sticker being placed onto the slide. It is best for badges, seals, milestone dots, small logos, or highlighted labels that should feel lively and memorable. The motion is playful and energetic, but contained enough for business decks when used sparingly. Choose this when a small object needs personality and immediate visual grab.'
)
CONTENT_MATCHERS = {'is_badge': True, 'short_text': True, 'digits': False, 'has_image': False, 'is_headline': False}
COMPLEMENTARY_WITH = ['metric_snap_focus', 'breathing_halo']
CONFLICTS_WITH = ['rotate_in', 'badge_swing_in', 'pulse_emphasis']


MOOD = ['playful', 'punchy', 'bold']
ARCHETYPE_FIT = ['product', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_rotate_in, emit_grow_from_small
    base = int(p.get('delay_ms', 80))
    main = int(p.get('duration_ms', 560))
    emit_rotate_in(slide, target_shape, delay_ms=base, duration_ms=main, from_deg=int(p.get('from_deg', 180)))
    emit_grow_from_small(slide, target_shape, delay_ms=base, duration_ms=main, from_pct=int(p.get('from_pct', 72)))
