"""Auto-distilled motion skill: badge_swing_in.

Small logo, icon, or badge fades in with a restrained swing.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'badge_swing_in'
CATEGORY = 'entrance'
DESCRIPTION = 'Small logo, icon, or badge fades in with a restrained swing.'

APPLICABILITY = {
    "roles": ['cover', 'feature_callout', 'product_focus', 'hero_giant_metric'],
    "anchor_names": ['logo', 'badge', 'icon', 'seal', 'accent'],
    "anchor_name_regex": '^(logo|badge|icon|seal|accent)$',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 150, 'min': 0, 'max': 700}, 'duration_ms': {'default': 650, 'min': 400, 'max': 900}, 'from_deg': {'default': -14, 'min': -24, 'max': 24}}

TAGS = ['playful', 'brand', 'accent', 'restrained', 'object-motion']
INTENSITY = 5
EMBEDDING_TEXT = (
    'A restrained swing entrance for small visual anchors like logos, certification seals, icons, and badge-like stickers. It combines a soft fade with a slight rotational arrival, creating a tasteful hint of pendulum motion instead of a dramatic spin. Use it when a small emblem needs personality or brand presence without stealing focus from the main headline or metric. The feel is friendly and polished, with medium intensity suited to accent graphics.'
)
CONTENT_MATCHERS = {'is_logo': True, 'is_icon': True}
COMPLEMENTARY_WITH = ['count_up_metric', 'image_ken_burns']
CONFLICTS_WITH = ['rotate_in', 'dramatic_zoom']


MOOD = ['playful', 'punchy', 'restrained', 'boardroom']
ARCHETYPE_FIT = ['brand', 'boardroom', 'product', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_rotate_in
    delay = int(p.get('delay_ms', 150))
    duration = int(p.get('duration_ms', 650))
    emit_fade_in(slide, target_shape, delay_ms=delay, duration_ms=max(220, int(duration * 0.7)))
    emit_rotate_in(slide, target_shape, delay_ms=delay, duration_ms=duration, from_deg=int(p.get('from_deg', -14)))
