"""Auto-distilled motion skill: card_rise_settle.

Panel lifts from below and gently settles, ideal for cards, agenda tiles, and modules.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'card_rise_settle'
CATEGORY = 'entrance'
DESCRIPTION = 'Panel lifts from below and gently settles, ideal for cards, agenda tiles, and modules.'

APPLICABILITY = {
    "roles": ['comparison_card', 'agenda', 'feature_grid', 'dashboard'],
    "anchor_names": ['card', 'panel', 'tile', 'module', 'feature'],
    "anchor_name_regex": '(?i)(card|panel|tile|module|feature)',
    "max_per_slide": 3,
}

PARAMETERS = {'delay_ms': {'default': 100, 'min': 0, 'max': 1200}, 'duration_ms': {'default': 700, 'min': 500, 'max': 900}, 'settle_duration_ms': {'default': 260, 'min': 180, 'max': 400}, 'settle_to_pct': {'default': 102, 'min': 101, 'max': 104}}

TAGS = ['card', 'ui', 'modular', 'gentle', 'structured']
INTENSITY = 4
EMBEDDING_TEXT = (
    'A rectangular module rises from below, then gives a very small settle emphasis so the layout feels responsive and modern. This is especially effective for cards, feature tiles, comparison panels, agenda blocks, and other repeatable UI-like elements. The feel is orderly and product-design adjacent, with a little softness at the end instead of a hard stop. Use it when structured content should enter with clarity and polish.'
)
CONTENT_MATCHERS = {'is_card': True, 'multi_line_text': True, 'digits': False, 'has_image': False, 'is_headline': False}
COMPLEMENTARY_WITH = ['chart_bar_grow', 'metric_snap_focus']
CONFLICTS_WITH = ['bounce_in', 'slide_in_left', 'grow_reveal']


MOOD = ['editorial', 'calm']
ARCHETYPE_FIT = ['research', 'narrative']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fly_in, emit_grow_emphasis
    base = int(p.get('delay_ms', 100))
    main = int(p.get('duration_ms', 700))
    emit_fly_in(slide, target_shape, direction='bottom', delay_ms=base, duration_ms=main)
    emit_grow_emphasis(slide, target_shape, delay_ms=base + main, duration_ms=int(p.get('settle_duration_ms', 260)), to_pct=int(p.get('settle_to_pct', 102)))
