"""Auto-distilled motion skill: chart_peak_ping.

A quick upward peak and settle gives bars or markers a clear moment of importance.

Category: emphasis. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'chart_peak_ping'
CATEGORY = 'emphasis'
DESCRIPTION = 'A quick upward peak and settle gives bars or markers a clear moment of importance.'

APPLICABILITY = {
    "roles": ['chart', 'data_label', 'kpi_card', 'timeline_marker', 'comparison_chart'],
    "anchor_names": ['bar', 'point', 'marker', 'dot', 'value', 'data_label'],
    "anchor_name_regex": '(bar|point|marker|dot|value|data_label)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 160, 'min': 0, 'max': 1200}, 'duration_ms': {'default': 380, 'min': 280, 'max': 680}, 'dy_frac': {'default': 0.06, 'min': 0.03, 'max': 0.12}, 'grow_to_pct': {'default': 105, 'min': 102, 'max': 110}}

TAGS = ['chart', 'data', 'upward', 'focused', 'analytical']
INTENSITY = 4
EMBEDDING_TEXT = (
    'This emphasis is made for chart bars, dots, labels, and timeline markers that need a precise data-driven highlight. The motion rises and returns quickly, creating a visual peak that feels like a moment of significance or an analytical callout. It pairs well with dashboards, comparison slides, and quarterly results where one data point should stand apart. The style is directional and informative rather than decorative.'
)
CONTENT_MATCHERS = {'data_viz': True, 'digits': True, 'is_metric': True, 'is_headline': False, 'has_icon': False}
COMPLEMENTARY_WITH = ['chart_bar_grow', 'count_up_metric']
CONFLICTS_WITH = ['metric_snap_pop', 'slide_in_left']


MOOD = ['boardroom', 'technical', 'editorial', 'punchy']
ARCHETYPE_FIT = ['data', 'boardroom']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_motion_path, emit_grow_emphasis
    base_delay = int(p.get('delay_ms', 160))
    base_dur = int(p.get('duration_ms', 380))
    dy = float(p.get('dy_frac', 0.06))
    grow_to = int(p.get('grow_to_pct', 105))
    svg_path = f'M 0 0 L 0 -{dy}'
    emit_motion_path(slide, target_shape, svg_path=svg_path, delay_ms=base_delay, duration_ms=base_dur, auto_reverse=True)
    emit_grow_emphasis(slide, target_shape, delay_ms=base_delay, duration_ms=max(220, base_dur - 40), to_pct=grow_to)
