"""Auto-distilled motion skill: cinematic_lateral_reveal.

Soft side wipe with a slight parallax glide for photos, wide panels, and section resets.

Category: transition. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'cinematic_lateral_reveal'
CATEGORY = 'transition'
DESCRIPTION = 'Soft side wipe with a slight parallax glide for photos, wide panels, and section resets.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'hero_image', 'full_bleed_photo', 'media_feature'],
    "anchor_names": ['image', 'media', 'panel', 'background', 'section_title'],
    "anchor_name_regex": '(image|media|panel|background|section)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 500}, 'duration_ms': {'default': 900, 'min': 650, 'max': 1600}, 'glide_ms': {'default': 1100, 'min': 700, 'max': 1800}, 'dx_frac': {'default': 0.05, 'min': 0.01, 'max': 0.12}, 'bow_frac': {'default': 0.02, 'min': -0.04, 'max': 0.08}}

TAGS = ['cinematic', 'parallax', 'editorial', 'wide', 'smooth']
INTENSITY = 4
EMBEDDING_TEXT = (
    'This transition feels like a cinematic panel reveal: the content wipes on from the side while drifting just enough to create soft parallax. It works especially well on photography, full-width media, and large section panels where you want a clean scene change without flashy energy. The look is polished, modern, and editorial rather than playful. Use it for cover resets, image-led slides, and spacious layouts with low text density.'
)
CONTENT_MATCHERS = {'is_image': True, 'wide_shape': True, 'low_text_density': True, 'is_section_title': False}
COMPLEMENTARY_WITH = ['headline_mist_rise', 'subhead_stagger_fade']
CONFLICTS_WITH = ['editorial_wipe_rise', 'photo_wipe_drift', 'hero_arc_glide']


MOOD = ['editorial', 'cinematic', 'calm']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_arc_path
    _delay = int(p.get('delay_ms', 0))
    _duration = int(p.get('duration_ms', 900))
    _glide = int(p.get('glide_ms', 1100))
    _dx = float(p.get('dx_frac', 0.05))
    _bow = float(p.get('bow_frac', 0.02))
    emit_wipe_in(slide, target_shape, direction='left', delay_ms=_delay, duration_ms=_duration)
    emit_arc_path(slide, target_shape, delay_ms=_delay, duration_ms=_glide, dx_frac=_dx, dy_frac=0.0, bow_frac=_bow)
