"""Auto-distilled motion skill: cinematic_veil_reveal.

Soft lateral wipe with a dissolved fade for elegant chapter, quote, and hero transitions.

Category: transition. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'cinematic_veil_reveal'
CATEGORY = 'transition'
DESCRIPTION = 'Soft lateral wipe with a dissolved fade for elegant chapter, quote, and hero transitions.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'hero_statement', 'editorial_quote', 'full_bleed_image'],
    "anchor_names": ['headline', 'subhead', 'chapter_label', 'quote', 'hero_image'],
    "anchor_name_regex": '^(headline|subhead|chapter_label|quote|hero_image)$',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 400}, 'fade_duration_ms': {'default': 720, 'min': 400, 'max': 1000}, 'wipe_duration_ms': {'default': 1100, 'min': 700, 'max': 1600}, 'wipe_offset_ms': {'default': 40, 'min': 0, 'max': 180}}

TAGS = ['cinematic', 'editorial', 'soft', 'elegant', 'chapter']
INTENSITY = 4
EMBEDDING_TEXT = (
    'A soft cinematic transition that feels like a translucent veil passing across the slide. It combines a gentle dissolve with a longer lateral wipe, so headlines, chapter labels, and full-bleed imagery feel composed rather than flashy. This is especially strong for editorial covers, section breaks, pull quotes, and premium brand storytelling. The mood is refined, low-intensity, and Apple-keynote polished.'
)
CONTENT_MATCHERS = {'is_headline': True, 'has_image': True, 'low_text_density': True, 'digits': False}
COMPLEMENTARY_WITH = ['headline_word_cascade', 'image_ken_burns', 'gentle_rise_fade']
CONFLICTS_WITH = ['editorial_wipe_rise', 'panel_unveil_settle']


MOOD = ['editorial', 'cinematic', 'calm']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_wipe_in
    _delay = int(p.get('delay_ms', 80))
    _fade_ms = int(p.get('fade_duration_ms', 720))
    _wipe_ms = int(p.get('wipe_duration_ms', 1100))
    _wipe_offset = int(p.get('wipe_offset_ms', 40))
    emit_fade_in(slide, target_shape, delay_ms=_delay, duration_ms=_fade_ms)
    emit_wipe_in(slide, target_shape, direction='left', delay_ms=_delay + _wipe_offset, duration_ms=_wipe_ms)
