"""Auto-distilled motion skill: editorial_wipe_rise.

Bottom wipe reveal with a tiny settle pulse for premium headlines.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'editorial_wipe_rise'
CATEGORY = 'entrance'
DESCRIPTION = 'Bottom wipe reveal with a tiny settle pulse for premium headlines.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'quote_slide', 'hero_statement'],
    "anchor_names": ['headline', 'title', 'subhead', 'quote'],
    "anchor_name_regex": '^(headline|title|subhead|quote)$',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 600}, 'duration_ms': {'default': 720, 'min': 450, 'max': 1100}, 'settle_ms': {'default': 240, 'min': 150, 'max': 450}, 'scale_pct': {'default': 103, 'min': 101, 'max': 106}}

TAGS = ['subtle', 'editorial', 'premium', 'typography', 'clean']
INTENSITY = 3
EMBEDDING_TEXT = (
    'An editorial headline reveal that behaves like a clean upward mask, then lands with a tiny settle pulse. It is ideal for cover titles, section headers, short quotes, and spacious typography where you want polished motion without theatrical zooming. The look feels premium, modern, and presentation-design-forward, especially on minimal or photographic slides. Intensity is low to medium, with crisp timing that keeps text readable.'
)
CONTENT_MATCHERS = {'is_headline': True, 'is_short_text': True}
COMPLEMENTARY_WITH = ['image_ken_burns', 'count_up_metric']
CONFLICTS_WITH = ['headline_word_cascade', 'slide_in_left']


MOOD = ['editorial', 'calm', 'cinematic', 'restrained']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_pulse
    delay = int(p.get('delay_ms', 80))
    duration = int(p.get('duration_ms', 720))
    settle = int(p.get('settle_ms', 240))
    emit_wipe_in(slide, target_shape, direction='bottom', delay_ms=delay, duration_ms=duration)
    emit_pulse(slide, target_shape, delay_ms=delay + duration - int(settle * 0.35), duration_ms=settle, scale_pct=int(p.get('scale_pct', 103)), repeats=1)
