"""Auto-distilled motion skill: editorial_side_nudge.

A precise lateral nudge spotlights labels and callouts without feeling flashy.

Category: emphasis. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'editorial_side_nudge'
CATEGORY = 'emphasis'
DESCRIPTION = 'A precise lateral nudge spotlights labels and callouts without feeling flashy.'

APPLICABILITY = {
    "roles": ['callout', 'annotation', 'label', 'caption', 'quote_pull', 'sidebar'],
    "anchor_names": ['callout', 'label', 'caption', 'note', 'annotation', 'tag'],
    "anchor_name_regex": '(callout|label|caption|note|annotation|tag)',
    "max_per_slide": 3,
}

PARAMETERS = {'delay_ms': {'default': 140, 'min': 0, 'max': 1200}, 'duration_ms': {'default': 420, 'min': 280, 'max': 700}, 'dx_frac': {'default': 0.035, 'min': 0.015, 'max': 0.08}, 'grow_to_pct': {'default': 103, 'min': 101, 'max': 108}}

TAGS = ['editorial', 'subtle', 'directional', 'precise', 'tidy']
INTENSITY = 3
EMBEDDING_TEXT = (
    "This is a quiet editorial emphasis for captions, labels, and explanatory callouts. The shape shifts sideways and returns, creating a crisp nudge that says 'look here' without stealing the whole slide. It suits magazine-style layouts, product annotations, and presentation notes where subtle hierarchy matters. The intensity is low and the motion reads smart, deliberate, and highly controlled."
)
CONTENT_MATCHERS = {'is_annotation': True, 'short_text': True, 'digits': False, 'is_headline': False, 'has_icon': False}
COMPLEMENTARY_WITH = ['gentle_rise_fade', 'bullet_stagger_reveal']
CONFLICTS_WITH = ['slide_in_left', 'panel_unveil_settle']


MOOD = ['calm', 'editorial', 'boardroom', 'technical']
ARCHETYPE_FIT = ['narrative', 'research', 'brand', 'boardroom']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_motion_path, emit_grow_emphasis
    base_delay = int(p.get('delay_ms', 140))
    base_dur = int(p.get('duration_ms', 420))
    dx = float(p.get('dx_frac', 0.035))
    grow_to = int(p.get('grow_to_pct', 103))
    svg_path = f'M 0 0 L {dx} 0'
    emit_motion_path(slide, target_shape, svg_path=svg_path, delay_ms=base_delay, duration_ms=base_dur, auto_reverse=True)
    emit_grow_emphasis(slide, target_shape, delay_ms=base_delay, duration_ms=max(220, base_dur - 80), to_pct=grow_to)
