"""Auto-distilled motion skill: eyebrow_tick_in.

Tiny overline or kicker text ticks into place with a faint rotation and brisk letter timing.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'eyebrow_tick_in'
CATEGORY = 'text'
DESCRIPTION = 'Tiny overline or kicker text ticks into place with a faint rotation and brisk letter timing.'

APPLICABILITY = {
    "roles": ['cover', 'hero', 'section_divider', 'chart_annotation'],
    "anchor_names": ['eyebrow', 'kicker', 'overline', 'label'],
    "anchor_name_regex": '(?i)(eyebrow|kicker|overline|label)',
    "max_per_slide": 3,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 500}, 'fade_duration_ms': {'default': 320, 'min': 220, 'max': 500}, 'rotate_duration_ms': {'default': 420, 'min': 300, 'max': 650}, 'from_deg': {'default': -8, 'min': -14, 'max': -3}, 'text_offset_ms': {'default': 40, 'min': 0, 'max': 120}, 'stagger_ms': {'default': 18, 'min': 8, 'max': 40}, 'per_duration_ms': {'default': 140, 'min': 100, 'max': 220}}

TAGS = ['eyebrow', 'kicker', 'minimal', 'precise', 'accent']
INTENSITY = 2
EMBEDDING_TEXT = (
    'A minimal accent motion for small uppercase labels, eyebrow text, overlines, and chart callouts. The text fades up, nudges into orientation with a slight rotational tick, and the characters resolve very quickly for a crisp editorial finish. It is subtle enough to stack above a headline without stealing attention. Ideal for brand labels, section markers, and tiny navigational text.'
)
CONTENT_MATCHERS = {'is_kicker': True, 'short_text': True, 'all_caps_likely': True}
COMPLEMENTARY_WITH = ['headline_prism_stagger', 'panel_unveil_settle', 'background_parallax_glide']
CONFLICTS_WITH = ['badge_swing_in', 'rotate_in', 'headline_word_cascade']


MOOD = ['boardroom', 'technical', 'calm', 'restrained']
ARCHETYPE_FIT = ['boardroom', 'data', 'narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_rotate_in, emit_text_stagger
    base_delay = int(p.get('delay_ms', 0))
    fade_duration_ms = int(p.get('fade_duration_ms', 320))
    rotate_duration_ms = int(p.get('rotate_duration_ms', 420))
    from_deg = int(p.get('from_deg', -8))
    text_offset_ms = int(p.get('text_offset_ms', 40))
    stagger_ms = int(p.get('stagger_ms', 18))
    per_duration_ms = int(p.get('per_duration_ms', 140))
    emit_fade_in(slide, target_shape, delay_ms=base_delay, duration_ms=fade_duration_ms)
    emit_rotate_in(slide, target_shape, delay_ms=base_delay, duration_ms=rotate_duration_ms, from_deg=from_deg)
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + text_offset_ms, stagger_ms=stagger_ms, per_duration_ms=per_duration_ms)
