"""Auto-distilled motion skill: eyebrow_slant_settle.

Short labels rotate in slightly, then read on with a crisp stagger and tiny settle.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'eyebrow_slant_settle'
CATEGORY = 'text'
DESCRIPTION = 'Short labels rotate in slightly, then read on with a crisp stagger and tiny settle.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'hero_giant_metric', 'comparison'],
    "anchor_names": ['eyebrow', 'kicker', 'label', 'section_label'],
    "anchor_name_regex": '^(eyebrow|kicker|label|section_label)$',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 40, 'min': 0, 'max': 1000}, 'rotate_duration_ms': {'default': 420, 'min': 250, 'max': 700}, 'from_deg': {'default': -8, 'min': -18, 'max': 18}, 'stagger_ms': {'default': 40, 'min': 15, 'max': 100}, 'per_duration_ms': {'default': 220, 'min': 120, 'max': 400}, 'settle_duration_ms': {'default': 260, 'min': 160, 'max': 520}, 'to_pct': {'default': 102, 'min': 101, 'max': 105}}

TAGS = ['kicker', 'label', 'angular', 'compact', 'branded']
INTENSITY = 5
EMBEDDING_TEXT = (
    'This motion is meant for small uppercase labels, kicker text, eyebrow lines, and section markers. A slight rotational entrance gives the text a branded, angular personality, then a tight stagger keeps the read crisp and controlled before a tiny settle locks it in. It works best on short text blocks where a few degrees of tilt can add style without noise. Choose it for category labels, chapter markers, and compact headings that need a touch of character.'
)
CONTENT_MATCHERS = {'is_label': True, 'all_caps_or_short': True, 'short_text': True}
COMPLEMENTARY_WITH = ['badge_swing_in', 'page_hinge_drop']
CONFLICTS_WITH = ['rotate_in', 'seal_twirl_land']


MOOD = ['editorial', 'calm']
ARCHETYPE_FIT = ['data', 'boardroom', 'narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_rotate_in, emit_text_stagger, emit_grow_emphasis
    base_delay = int(p.get('delay_ms', 40))
    rot_dur = int(p.get('rotate_duration_ms', 420))
    emit_rotate_in(slide, target_shape, delay_ms=base_delay, duration_ms=rot_dur, from_deg=int(p.get('from_deg', -8)))
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + 70, stagger_ms=int(p.get('stagger_ms', 40)), per_duration_ms=int(p.get('per_duration_ms', 220)))
    emit_grow_emphasis(slide, target_shape, delay_ms=base_delay + rot_dur + 80, duration_ms=int(p.get('settle_duration_ms', 260)), to_pct=int(p.get('to_pct', 102)))
