"""Auto-distilled motion skill: floating_card_drift.

Subtle diagonal ping-pong drift that makes cards and hero visuals feel suspended.

Category: ambient. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'floating_card_drift'
CATEGORY = 'ambient'
DESCRIPTION = 'Subtle diagonal ping-pong drift that makes cards and hero visuals feel suspended.'

APPLICABILITY = {
    "roles": ['hero_image', 'quote_card', 'section_divider', 'product_callout'],
    "anchor_names": ['hero_visual', 'panel', 'card', 'image'],
    "anchor_name_regex": None,
    "max_per_slide": 2,
}

PARAMETERS = {'dx_in': {'default': 0.12, 'min': 0.04, 'max': 0.3}, 'dy_in': {'default': -0.08, 'min': -0.2, 'max': 0.12}, 'duration_ms': {'default': 5400, 'min': 3000, 'max': 9000}}

TAGS = ['subtle', 'airy', 'premium', 'editorial', 'calm']
INTENSITY = 2
EMBEDDING_TEXT = (
    'A barely-there diagonal drift that makes cards, screenshots, and product panels feel suspended rather than static. It works especially well on hero visuals, pull quotes, and simple framed content where the layout should feel alive but never busy. The look is calm, premium, and modern, closer to keynote-style living canvas motion than decorative animation. Use it when the target is large, clean, and not already using a pan or zoom treatment.'
)
CONTENT_MATCHERS = {'is_image': True, 'is_panel': True, 'low_word_count': True}
COMPLEMENTARY_WITH = ['panel_unveil_settle', 'gentle_rise_fade']
CONFLICTS_WITH = ['image_ken_burns', 'orbital_accent']


MOOD = ['calm', 'editorial', 'restrained', 'cinematic']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _shell_helpers import add_drift_motion
    add_drift_motion(
        slide,
        target_shape,
        dx_in=float(p.get('dx_in', 0.12)),
        dy_in=float(p.get('dy_in', -0.08)),
        duration_ms=int(p.get('duration_ms', 5400)),
        pingpong=True,
    )
