"""Auto-distilled motion skill: focus_pull_dissolve.

Camera-like depth dissolve with a restrained push-in and micro-settle for hero quotes and product imagery.

Category: transition. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'focus_pull_dissolve'
CATEGORY = 'transition'
DESCRIPTION = 'Camera-like depth dissolve with a restrained push-in and micro-settle for hero quotes and product imagery.'

APPLICABILITY = {
    "roles": ['cover', 'quote_feature', 'product_hero', 'testimonial', 'hero_giant_metric'],
    "anchor_names": ['headline', 'quote', 'image', 'product_shot', 'portrait'],
    "anchor_name_regex": '(headline|quote|image|product|portrait)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 400}, 'duration_ms': {'default': 1000, 'min': 700, 'max': 1800}, 'from_pct': {'default': 112, 'min': 104, 'max': 125}, 'settle_ms': {'default': 260, 'min': 180, 'max': 420}, 'settle_scale_pct': {'default': 103, 'min': 101, 'max': 106}}

TAGS = ['depth', 'camera', 'premium', 'hero', 'focus']
INTENSITY = 6
EMBEDDING_TEXT = (
    'This transition mimics a camera focus-pull: the content dissolves in while gently pushing through depth, then lands with a tiny settling pulse. It is ideal for hero imagery, large quotes, portraits, and premium product shots where you want a cinematic handoff rather than a simple zoom. The effect has more presence than a basic fade but stays controlled and tasteful. Retrieve it for low-density focal content that should feel important, polished, and slightly dramatic.'
)
CONTENT_MATCHERS = {'is_quote': True, 'is_image': True, 'is_headline': True, 'low_text_density': True}
COMPLEMENTARY_WITH = ['subhead_stagger_fade', 'metric_snap_focus']
CONFLICTS_WITH = ['dramatic_zoom', 'quote_lens_arrive', 'zoom_from_center']


MOOD = ['editorial', 'cinematic', 'bold', 'calm']
ARCHETYPE_FIT = ['narrative', 'research', 'data', 'boardroom']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_dramatic_zoom, emit_pulse
    _delay = int(p.get('delay_ms', 0))
    _duration = int(p.get('duration_ms', 1000))
    _from = int(p.get('from_pct', 112))
    _settle = int(p.get('settle_ms', 260))
    _scale = int(p.get('settle_scale_pct', 103))
    emit_fade_in(slide, target_shape, delay_ms=_delay, duration_ms=_duration)
    emit_dramatic_zoom(slide, target_shape, delay_ms=_delay, duration_ms=_duration, from_pct=_from)
    emit_pulse(slide, target_shape, delay_ms=_delay + _duration, duration_ms=_settle, scale_pct=_scale, repeats=1)
