"""Auto-distilled motion skill: gentle_rise_fade.

Soft upward rise with fade, ideal for subheads, captions, and supporting text blocks.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'gentle_rise_fade'
CATEGORY = 'entrance'
DESCRIPTION = 'Soft upward rise with fade, ideal for subheads, captions, and supporting text blocks.'

APPLICABILITY = {
    "roles": ['subhead', 'body_intro', 'caption', 'agenda', 'supporting_text'],
    "anchor_names": ['subhead', 'body', 'caption', 'supporting_text', 'blurb'],
    "anchor_name_regex": '(subhead|body|caption|supporting_text|blurb)',
    "max_per_slide": 3,
}

PARAMETERS = {'delay_ms': {'default': 140, 'min': 0, 'max': 700}, 'fly_duration_ms': {'default': 620, 'min': 400, 'max': 900}, 'fade_duration_ms': {'default': 480, 'min': 250, 'max': 750}}

TAGS = ['subtle', 'typography', 'readable', 'quiet', 'modern']
INTENSITY = 2
EMBEDDING_TEXT = (
    'This is a quiet readability-first entrance where the text eases upward while fading into full presence. It is a strong default for subheads, captions, agenda blocks, and other supporting copy that should feel polished but not compete with the headline. The effect reads as modern, calm, and understated, with very low visual noise.'
)
CONTENT_MATCHERS = {'is_body': True, 'multi_line': True, 'is_headline': False, 'digits': False}
COMPLEMENTARY_WITH = ['bullet_stagger_reveal', 'image_ken_burns']
CONFLICTS_WITH = ['slide_in_left', 'headline_word_cascade']


MOOD = ['calm', 'restrained', 'editorial']
ARCHETYPE_FIT = ['research', 'narrative']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fly_in, emit_fade_in
    emit_fly_in(slide, target_shape,
                direction='bottom',
                delay_ms=int(p.get('delay_ms', 140)),
                duration_ms=int(p.get('fly_duration_ms', 620)))
    emit_fade_in(slide, target_shape,
                 delay_ms=int(p.get('delay_ms', 140)),
                 duration_ms=int(p.get('fade_duration_ms', 480)))
