"""Auto-distilled motion skill: glass_crossfade_settle.

Clean dissolve with a tiny scale-up for cards, overlays, product callouts, and calm panel changes.

Category: transition. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'glass_crossfade_settle'
CATEGORY = 'transition'
DESCRIPTION = 'Clean dissolve with a tiny scale-up for cards, overlays, product callouts, and calm panel changes.'

APPLICABILITY = {
    "roles": ['comparison_card', 'quote_card', 'modal_overlay', 'product_callout', 'stat_panel'],
    "anchor_names": ['panel', 'card', 'quote', 'callout', 'product_shot'],
    "anchor_name_regex": '(panel|card|quote|callout|product)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 400}, 'duration_ms': {'default': 760, 'min': 600, 'max': 1200}, 'from_pct': {'default': 96, 'min': 90, 'max': 99}}

TAGS = ['minimal', 'clean', 'glassmorphism', 'subtle', 'calm']
INTENSITY = 3
EMBEDDING_TEXT = (
    'This transition is a refined crossfade with an almost invisible scale-up, like a glass card settling into focus. It suits UI-like panels, quote cards, product modules, and any content block that should feel crisp and premium rather than animated. The motion is restrained, low-intensity, and Apple-like. Retrieve this when the slide has neat rectangular surfaces, moderate text, and a need for elegant continuity.'
)
CONTENT_MATCHERS = {'has_background_panel': True, 'medium_text_density': True, 'is_quote': True, 'is_image': False}
COMPLEMENTARY_WITH = ['bullet_stagger_reveal', 'subhead_stagger_fade']
CONFLICTS_WITH = ['grow_reveal', 'card_rise_settle', 'zoom_from_center']


MOOD = ['calm', 'restrained', 'editorial', 'cinematic']
ARCHETYPE_FIT = ['research', 'narrative']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_grow_from_small
    _delay = int(p.get('delay_ms', 0))
    _duration = int(p.get('duration_ms', 760))
    _from = int(p.get('from_pct', 96))
    emit_fade_in(slide, target_shape, delay_ms=_delay, duration_ms=_duration)
    emit_grow_from_small(slide, target_shape, delay_ms=_delay, duration_ms=_duration, from_pct=_from)
