"""Auto-distilled motion skill: glass_card_hover_loop.

Subtle levitation for cards and mockups with slow drift plus a barely-there pulse.

Category: ambient. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'glass_card_hover_loop'
CATEGORY = 'ambient'
DESCRIPTION = 'Subtle levitation for cards and mockups with slow drift plus a barely-there pulse.'

APPLICABILITY = {
    "roles": ['product_card', 'feature_card', 'testimonial_card', 'comparison_panel', 'device_mockup'],
    "anchor_names": ['card', 'panel', 'tile', 'mockup', 'screenshot'],
    "anchor_name_regex": '(?i)(card|panel|tile|mockup|screenshot|device)',
    "max_per_slide": 3,
}

PARAMETERS = {'duration_ms': {'default': 5200, 'min': 2600, 'max': 9000}, 'dx_in': {'default': 0.06, 'min': -0.18, 'max': 0.18}, 'dy_in': {'default': -0.04, 'min': -0.15, 'max': 0.15}, 'pulse_duration_ms': {'default': 3800, 'min': 2200, 'max': 7000}, 'scale_pct': {'default': 103, 'min': 101, 'max': 106}}

TAGS = ['subtle', 'premium', 'ui', 'hover', 'card']
INTENSITY = 2
EMBEDDING_TEXT = (
    'This ambient motion makes a panel, screenshot, or UI card feel like it is hovering in polished glass space. It combines a very slow ping-pong drift with a tiny scale pulse, creating a premium product-demo feel rather than a playful bounce. Use it on feature tiles, software mockups, pricing cards, and testimonial panels where the content should feel alive but still calm. The intensity is low and elegant, ideal for modern SaaS, product marketing, and clean editorial layouts.'
)
CONTENT_MATCHERS = {'is_card': True, 'is_mockup': True, 'has_image_fill': True, 'medium_or_large_shape': True}
COMPLEMENTARY_WITH = ['panel_unveil_settle', 'editorial_wipe_rise', 'gentle_rise_fade']
CONFLICTS_WITH = ['floating_card_drift', 'pulse_emphasis', 'image_ken_burns']


MOOD = ['calm', 'editorial', 'cinematic', 'restrained']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _shell_helpers import add_drift_motion, add_pulse_loop
    add_drift_motion(slide, target_shape, dx_in=float(p.get('dx_in', 0.06)), dy_in=float(p.get('dy_in', -0.04)), duration_ms=int(p.get('duration_ms', 5200)), pingpong=True)
    add_pulse_loop(slide, target_shape, duration_ms=int(p.get('pulse_duration_ms', 3800)), scale_pct=int(p.get('scale_pct', 103)))
