"""Auto-distilled motion skill: headline_arc_settle.

Elegant headline enters on a shallow arc with a quick fade for premium cover moments.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'headline_arc_settle'
CATEGORY = 'entrance'
DESCRIPTION = 'Elegant headline enters on a shallow arc with a quick fade for premium cover moments.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'hero_statement', 'quote'],
    "anchor_names": ['headline', 'title', 'quote', 'hero_headline'],
    "anchor_name_regex": '(?i)(headline|title|quote|hero)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 800}, 'duration_ms': {'default': 820, 'min': 550, 'max': 1100}, 'fade_ms': {'default': 220, 'min': 120, 'max': 400}, 'dx_frac': {'default': 0.0, 'min': -0.03, 'max': 0.03}, 'dy_frac': {'default': -0.08, 'min': -0.16, 'max': 0.04}, 'bow_frac': {'default': 0.18, 'min': 0.05, 'max': 0.28}}

TAGS = ['editorial', 'premium', 'graceful', 'headline', 'subtle']
INTENSITY = 4
EMBEDDING_TEXT = (
    'A large title glides into place on a shallow arc, then settles with a clean fade that feels premium and editorial. This works especially well for cover slides, section dividers, pull quotes, and short high-contrast headlines. The motion reads as confident rather than flashy, with gentle curvature and a polished, Apple-keynote feel. Use it when the typography should feel elevated, spacious, and important.'
)
CONTENT_MATCHERS = {'is_headline': True, 'short_text': True, 'digits': False, 'multi_line_text': False, 'has_image': False}
COMPLEMENTARY_WITH = ['image_ken_burns', 'breathing_halo', 'subhead_stagger_fade']
CONFLICTS_WITH = ['slide_in_left', 'dramatic_zoom', 'headline_word_cascade']


MOOD = ['editorial', 'calm', 'cinematic']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_arc_path
    base = int(p.get('delay_ms', 0))
    emit_fade_in(slide, target_shape, delay_ms=base, duration_ms=int(p.get('fade_ms', 220)))
    emit_arc_path(slide, target_shape, delay_ms=base, duration_ms=int(p.get('duration_ms', 820)), dx_frac=float(p.get('dx_frac', 0.0)), dy_frac=float(p.get('dy_frac', -0.08)), bow_frac=float(p.get('bow_frac', 0.18)))
