"""Auto-distilled motion skill: headline_letterpress_stagger.

Soft editorial headline reveal with a tiny scale-up and measured word stagger.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'headline_letterpress_stagger'
CATEGORY = 'text'
DESCRIPTION = 'Soft editorial headline reveal with a tiny scale-up and measured word stagger.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'hero_statement', 'quote'],
    "anchor_names": ['headline', 'title', 'quote'],
    "anchor_name_regex": '^(headline|title|quote)$',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 1200}, 'lead_duration_ms': {'default': 240, 'min': 120, 'max': 420}, 'stagger_ms': {'default': 55, 'min': 20, 'max': 140}, 'per_duration_ms': {'default': 420, 'min': 220, 'max': 760}, 'from_pct': {'default': 96, 'min': 88, 'max': 99}}

TAGS = ['editorial', 'premium', 'headline', 'subtle', 'staggered']
INTENSITY = 3
EMBEDDING_TEXT = (
    'This text motion feels like a refined magazine headline being pressed into view. The whole line softly fades and lifts from a near-full scale, while the text itself reveals in a calm, measured stagger that reads as premium rather than flashy. It fits short headlines, titles, and hero statements where typography is the main visual event. Best for elegant, minimal slides with strong hierarchy and low-to-medium motion intensity.'
)
CONTENT_MATCHERS = {'is_headline': True, 'short_text': True, 'line_count_lte_3': True}
COMPLEMENTARY_WITH = ['glass_crossfade_settle', 'focus_pull_dissolve']
CONFLICTS_WITH = ['headline_word_cascade', 'headline_mist_rise']


MOOD = ['editorial', 'calm', 'restrained', 'cinematic']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_grow_from_small, emit_text_stagger
    base_delay = int(p.get('delay_ms', 0))
    lead = int(p.get('lead_duration_ms', 240))
    emit_fade_in(slide, target_shape, delay_ms=base_delay, duration_ms=lead)
    emit_grow_from_small(slide, target_shape, delay_ms=base_delay, duration_ms=lead + 80, from_pct=int(p.get('from_pct', 96)))
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + 40, stagger_ms=int(p.get('stagger_ms', 55)), per_duration_ms=int(p.get('per_duration_ms', 420)))
