"""Auto-distilled motion skill: headline_mist_rise.

Soft upward float with a fade for polished headlines and subheads.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'headline_mist_rise'
CATEGORY = 'entrance'
DESCRIPTION = 'Soft upward float with a fade for polished headlines and subheads.'

APPLICABILITY = {
    "roles": ['cover', 'hero', 'section_divider', 'quote'],
    "anchor_names": ['headline', 'title', 'subhead', 'eyebrow'],
    "anchor_name_regex": '(?i)(headline|title|subhead|eyebrow|kicker)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 40, 'min': 0, 'max': 1200}, 'duration_ms': {'default': 680, 'min': 450, 'max': 950}}

TAGS = ['subtle', 'editorial', 'clean', 'text', 'premium']
INTENSITY = 3
EMBEDDING_TEXT = (
    'A restrained headline entrance that feels like the text is lifting out of haze. It combines a bottom-origin fly-in with a soft fade, creating a premium keynote or editorial look rather than a flashy reveal. Best for covers, section titles, short headlines, and elegant subheads where readability matters more than spectacle. The motion is subtle, calm, and modern, with low intensity and strong Apple-style polish.'
)
CONTENT_MATCHERS = {'is_headline': True, 'short_text': True, 'digits': False}
COMPLEMENTARY_WITH = ['bullet_stagger_reveal', 'subhead_stagger_fade']
CONFLICTS_WITH = ['editorial_wipe_rise', 'slide_in_left']


MOOD = ['editorial', 'calm', 'cinematic', 'restrained']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fly_in, emit_fade_in
    d = int(p.get('delay_ms', 40))
    dur = int(p.get('duration_ms', 680))
    emit_fly_in(slide, target_shape, direction='bottom', delay_ms=d, duration_ms=dur)
    emit_fade_in(slide, target_shape, delay_ms=d, duration_ms=max(320, int(dur * 0.8)))
