"""Auto-distilled motion skill: headline_restrike_focus.

Short headlines re-energize word by word, then finish with a restrained lift.

Category: emphasis. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'headline_restrike_focus'
CATEGORY = 'emphasis'
DESCRIPTION = 'Short headlines re-energize word by word, then finish with a restrained lift.'

APPLICABILITY = {
    "roles": ['cover', 'hero_statement', 'section_divider', 'quote_pull', 'title_slide'],
    "anchor_names": ['headline', 'title', 'quote', 'statement', 'hero_text'],
    "anchor_name_regex": '(headline|title|quote|statement|hero)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 1000}, 'stagger_ms': {'default': 70, 'min': 40, 'max': 140}, 'per_duration_ms': {'default': 220, 'min': 160, 'max': 320}, 'grow_to_pct': {'default': 105, 'min': 102, 'max': 110}}

TAGS = ['text', 'headline', 'editorial', 'refined', 'focus']
INTENSITY = 4
EMBEDDING_TEXT = (
    'This emphasis is built for short headlines, pull quotes, and section titles that deserve a second beat of attention. Words re-fire in a restrained stagger, then the whole line receives a light size lift for closure. The look is editorial and articulate rather than loud, making it ideal for keynote titles, manifesto lines, and premium brand statements. It is best on concise text with clear hierarchy and generous spacing.'
)
CONTENT_MATCHERS = {'is_headline': True, 'short_text': True, 'word_count_le_8': True, 'digits': False, 'has_icon': False}
COMPLEMENTARY_WITH = ['hero_lens_focus', 'gentle_rise_fade']
CONFLICTS_WITH = ['headline_word_cascade', 'bullet_stagger_reveal']


MOOD = ['editorial', 'calm', 'restrained', 'punchy']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_text_stagger, emit_grow_emphasis
    base_delay = int(p.get('delay_ms', 120))
    stagger = int(p.get('stagger_ms', 70))
    per_dur = int(p.get('per_duration_ms', 220))
    grow_to = int(p.get('grow_to_pct', 105))
    emit_text_stagger(slide, target_shape, delay_ms=base_delay, stagger_ms=stagger, per_duration_ms=per_dur)
    emit_grow_emphasis(slide, target_shape, delay_ms=base_delay + (stagger * 2), duration_ms=300, to_pct=grow_to)
