"""Auto-distilled motion skill: headline_prism_stagger.

Crisp headline reveal with a left wipe, segmented text stagger, and micro-settle finish.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'headline_prism_stagger'
CATEGORY = 'text'
DESCRIPTION = 'Crisp headline reveal with a left wipe, segmented text stagger, and micro-settle finish.'

APPLICABILITY = {
    "roles": ['cover', 'hero', 'section_divider', 'title_slide'],
    "anchor_names": ['headline', 'title', 'hero_headline'],
    "anchor_name_regex": '(?i)(headline|title|hero[_ ]?headline)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 600}, 'wipe_duration_ms': {'default': 520, 'min': 400, 'max': 900}, 'stagger_ms': {'default': 45, 'min': 20, 'max': 120}, 'per_duration_ms': {'default': 260, 'min': 180, 'max': 420}, 'settle_duration_ms': {'default': 320, 'min': 220, 'max': 600}, 'settle_to_pct': {'default': 104, 'min': 102, 'max': 107}}

TAGS = ['headline', 'premium', 'segmented', 'clean', 'confident']
INTENSITY = 5
EMBEDDING_TEXT = (
    'A polished headline treatment for keynote-style titles and short hero statements. The text feels cut through by light: a clean left-to-right wipe, then a tight word or line stagger, followed by a tiny confidence settle. It works best on bold typography, launch messaging, and section openers where you want clarity rather than drama. Medium intensity, premium, modern, and very presentation-forward.'
)
CONTENT_MATCHERS = {'is_headline': True, 'short_text': True, 'multi_line': False}
COMPLEMENTARY_WITH = ['background_parallax_glide', 'eyebrow_tick_in', 'panel_unveil_settle']
CONFLICTS_WITH = ['headline_word_cascade', 'dramatic_zoom', 'cinematic_veil_reveal']


MOOD = ['editorial', 'cinematic', 'technical', 'playful']
ARCHETYPE_FIT = ['brand', 'narrative', 'product']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_text_stagger, emit_grow_emphasis
    base_delay = int(p.get('delay_ms', 0))
    wipe_duration = int(p.get('wipe_duration_ms', 520))
    stagger_ms = int(p.get('stagger_ms', 45))
    per_duration_ms = int(p.get('per_duration_ms', 260))
    settle_duration_ms = int(p.get('settle_duration_ms', 320))
    settle_to_pct = int(p.get('settle_to_pct', 104))
    emit_wipe_in(slide, target_shape, direction='left', delay_ms=base_delay, duration_ms=wipe_duration)
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + 80, stagger_ms=stagger_ms, per_duration_ms=per_duration_ms)
    emit_grow_emphasis(slide, target_shape, delay_ms=base_delay + wipe_duration + stagger_ms * 2, duration_ms=settle_duration_ms, to_pct=settle_to_pct)
