"""Auto-distilled motion skill: headline_word_cascade.

Headline text reveals in a calm cascading rhythm with staggered words or lines.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'headline_word_cascade'
CATEGORY = 'entrance'
DESCRIPTION = 'Headline text reveals in a calm cascading rhythm with staggered words or lines.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'quote_slide', 'agenda', 'hero_statement'],
    "anchor_names": ['headline', 'title', 'quote', 'statement'],
    "anchor_name_regex": '^(headline|title|quote|statement)$',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 500}, 'fade_ms': {'default': 220, 'min': 120, 'max': 400}, 'stagger_ms': {'default': 70, 'min': 40, 'max': 140}, 'per_duration_ms': {'default': 260, 'min': 160, 'max': 360}}

TAGS = ['kinetic-typography', 'readable', 'storytelling', 'text', 'subtle']
INTENSITY = 4
EMBEDDING_TEXT = (
    'A kinetic-typography entrance where the text fades on and then reveals with a measured cascade across words or lines. It shines on manifesto headlines, quote slides, editorial statements, and short agenda titles that benefit from rhythm and pacing. The motion feels deliberate and literate rather than flashy, making it useful when the wording itself is the hero. Intensity is moderate, and the stagger adds narrative emphasis without feeling busy.'
)
CONTENT_MATCHERS = {'is_headline': True, 'is_text': True, 'multiword': True}
COMPLEMENTARY_WITH = ['image_ken_burns', 'breathing_halo']
CONFLICTS_WITH = ['editorial_wipe_rise', 'bullet_stagger_reveal']


MOOD = ['editorial']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_text_stagger
    delay = int(p.get('delay_ms', 120))
    emit_fade_in(slide, target_shape, delay_ms=delay, duration_ms=int(p.get('fade_ms', 220)))
    emit_text_stagger(slide, target_shape, delay_ms=delay, stagger_ms=int(p.get('stagger_ms', 70)), per_duration_ms=int(p.get('per_duration_ms', 260)))
