"""Auto-distilled motion skill: hero_metric_heartbeat_loop.

Gentle idle heartbeat pulse for a single KPI or giant stat after the main reveal.

Category: ambient. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'hero_metric_heartbeat_loop'
CATEGORY = 'ambient'
DESCRIPTION = 'Gentle idle heartbeat pulse for a single KPI or giant stat after the main reveal.'

APPLICABILITY = {
    "roles": ['hero_giant_metric', 'kpi', 'scorecard', 'closing_stat'],
    "anchor_names": ['metric', 'value', 'kpi', 'stat'],
    "anchor_name_regex": '^(metric|value|kpi|stat|number)$',
    "max_per_slide": 1,
}

PARAMETERS = {'duration_ms': {'default': 2600, 'min': 2000, 'max': 5000}, 'scale_pct': {'default': 103, 'min': 101, 'max': 110}}

TAGS = ['metric', 'subtle', 'alive', 'focused', 'executive']
INTENSITY = 3
EMBEDDING_TEXT = (
    'This is a restrained looping pulse designed for one important number, KPI, or score that should feel live on screen. It gives giant metrics a quiet heartbeat effect after count-up or snap-in motion, without turning the slide into a dashboard gimmick. The motion reads as confidence, continuity, and attention guidance rather than excitement. Best for large digits, sparse text, and executive summary slides where one number matters most.'
)
CONTENT_MATCHERS = {'digits': True, 'is_metric': True, 'low_word_count': True}
COMPLEMENTARY_WITH = ['count_up_metric', 'metric_snap_pop']
CONFLICTS_WITH = ['pulse_emphasis', 'numeric_confidence_bump']


MOOD = ['calm', 'boardroom', 'technical', 'bold']
ARCHETYPE_FIT = ['data', 'boardroom', 'brand', 'narrative']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _shell_helpers import add_pulse_loop
    add_pulse_loop(
        slide,
        target_shape,
        duration_ms=int(p.get('duration_ms', 2600)),
        scale_pct=int(p.get('scale_pct', 103)),
    )
