"""Auto-distilled motion skill: hero_lens_focus.

Slow focus-pull style zoom for hero photos, product renders, and cover imagery.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'hero_lens_focus'
CATEGORY = 'entrance'
DESCRIPTION = 'Slow focus-pull style zoom for hero photos, product renders, and cover imagery.'

APPLICABILITY = {
    "roles": ['cover', 'hero_visual', 'product_shot', 'portrait', 'full_bleed_image'],
    "anchor_names": ['hero_image', 'image', 'photo', 'visual', 'product'],
    "anchor_name_regex": '(hero_image|image|photo|visual|product)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 400}, 'duration_ms': {'default': 900, 'min': 600, 'max': 1200}, 'from_pct': {'default': 92, 'min': 75, 'max': 98}, 'fade_duration_ms': {'default': 700, 'min': 400, 'max': 1000}}

TAGS = ['cinematic', 'hero', 'image', 'premium', 'slow']
INTENSITY = 4
EMBEDDING_TEXT = (
    'This entrance mimics a subtle camera focus-pull or lens settle, with the image easing in through a restrained zoom and soft fade. It is tuned for hero photos, product renders, portraits, and full-bleed cover visuals where a cinematic feel is more appropriate than a punchy pop. The mood is premium, immersive, and composed, with enough movement to add life while preserving elegance.'
)
CONTENT_MATCHERS = {'is_photo': True, 'large_visual': True, 'digits': False, 'is_headline': False}
COMPLEMENTARY_WITH = ['image_ken_burns', 'bullet_stagger_reveal']
CONFLICTS_WITH = ['zoom_from_center', 'dramatic_zoom']


MOOD = ['cinematic', 'editorial', 'bold']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_zoom_in, emit_fade_in
    emit_zoom_in(slide, target_shape,
                 delay_ms=int(p.get('delay_ms', 80)),
                 duration_ms=int(p.get('duration_ms', 900)),
                 from_pct=int(p.get('from_pct', 92)))
    emit_fade_in(slide, target_shape,
                 delay_ms=int(p.get('delay_ms', 80)),
                 duration_ms=int(p.get('fade_duration_ms', 700)))
