"""Auto-distilled motion skill: hero_metric_surge_settle.

Large KPI swells forward, fades up, then lands with a quiet confidence bump.

Category: composite. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'hero_metric_surge_settle'
CATEGORY = 'composite'
DESCRIPTION = 'Large KPI swells forward, fades up, then lands with a quiet confidence bump.'

APPLICABILITY = {
    "roles": ['hero_giant_metric', 'kpi_callout', 'scorecard', 'cover'],
    "anchor_names": ['metric', 'value', 'stat', 'kpi', 'number'],
    "anchor_name_regex": '(?i)(metric|value|stat|kpi|total|revenue|arr|growth|percent|rate)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 1200}, 'duration_ms': {'default': 760, 'min': 500, 'max': 1000}, 'from_pct': {'default': 88, 'min': 80, 'max': 94}, 'settle_ms': {'default': 260, 'min': 180, 'max': 420}, 'settle_pct': {'default': 104, 'min': 102, 'max': 108}}

TAGS = ['premium', 'metric', 'confident', 'clean', 'hero']
INTENSITY = 5
EMBEDDING_TEXT = (
    'A polished composite entrance for a giant KPI, revenue number, growth percentage, or hero stat. The number fades in while gently zooming from a slightly reduced scale, then finishes with a restrained emphasis bump that feels expensive rather than flashy. It suits investor slides, quarterly metrics, and executive dashboards where the figure should feel authoritative and central. The mood is confident, modern, and high-clarity with medium intensity.'
)
CONTENT_MATCHERS = {'digits': True, 'is_metric': True, 'short_text': True, 'large_font': True}
COMPLEMENTARY_WITH = ['count_up_metric', 'background_parallax_glide']
CONFLICTS_WITH = ['metric_snap_pop', 'numeric_confidence_bump', 'dramatic_zoom', 'zoom_from_center']


MOOD = ['editorial', 'cinematic', 'bold', 'boardroom']
ARCHETYPE_FIT = ['data', 'boardroom', 'product', 'narrative']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_zoom_in, emit_grow_emphasis
    delay = int(p.get('delay_ms', 120))
    duration = int(p.get('duration_ms', 760))
    from_pct = int(p.get('from_pct', 88))
    settle_ms = int(p.get('settle_ms', 260))
    settle_pct = int(p.get('settle_pct', 104))
    emit_fade_in(slide, target_shape, delay_ms=delay, duration_ms=max(260, duration - 120))
    emit_zoom_in(slide, target_shape, delay_ms=delay, duration_ms=duration, from_pct=from_pct)
    emit_grow_emphasis(slide, target_shape, delay_ms=delay + duration - 60, duration_ms=settle_ms, to_pct=settle_pct)
