"""Auto-distilled motion skill: hero_arc_glide.

Cinematic curved glide for hero visuals, product shots, and large imagery.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'hero_arc_glide'
CATEGORY = 'entrance'
DESCRIPTION = 'Cinematic curved glide for hero visuals, product shots, and large imagery.'

APPLICABILITY = {
    "roles": ['cover', 'hero', 'product', 'illustration', 'full_bleed_image'],
    "anchor_names": ['hero_image', 'product_shot', 'visual', 'photo', 'device'],
    "anchor_name_regex": '(?i)(hero|image|photo|visual|product|device|illustration|screenshot)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 60, 'min': 0, 'max': 800}, 'duration_ms': {'default': 920, 'min': 650, 'max': 1200}, 'dx_frac': {'default': -0.16, 'min': -0.35, 'max': 0.35}, 'dy_frac': {'default': 0.08, 'min': -0.25, 'max': 0.25}, 'bow_frac': {'default': 0.16, 'min': 0.05, 'max': 0.3}}

TAGS = ['cinematic', 'smooth', 'premium', 'image', 'hero']
INTENSITY = 4
EMBEDDING_TEXT = (
    'This entrance makes a large visual feel guided into place on a curved track, like a camera move rather than a simple slide. The fade keeps the arrival graceful while the arc adds cinematic motion and depth. It works especially well for product renders, device shots, portraits, and hero images that should feel premium and composed. Retrieval cues include curved glide, cinematic hero image, premium product reveal, and smooth arc entrance.'
)
CONTENT_MATCHERS = {'has_image': True, 'is_photo_like': True, 'is_headline': False}
COMPLEMENTARY_WITH = ['image_ken_burns', 'photo_wipe_drift']
CONFLICTS_WITH = ['morph_anchor_arc', 'headline_arc_settle']


MOOD = ['cinematic', 'editorial', 'bold']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_arc_path, emit_fade_in
    d = int(p.get('delay_ms', 60))
    dur = int(p.get('duration_ms', 920))
    emit_fade_in(slide, target_shape, delay_ms=d, duration_ms=max(360, int(dur * 0.75)))
    emit_arc_path(slide, target_shape, delay_ms=d, duration_ms=dur, dx_frac=float(p.get('dx_frac', -0.16)), dy_frac=float(p.get('dy_frac', 0.08)), bow_frac=float(p.get('bow_frac', 0.16)))
