"""Auto-distilled motion skill: hinge_pivot_reveal.

A magazine-style pivot reveal with fade and a tiny reaffirming scale settle.

Category: transition. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'hinge_pivot_reveal'
CATEGORY = 'transition'
DESCRIPTION = 'A magazine-style pivot reveal with fade and a tiny reaffirming scale settle.'

APPLICABILITY = {
    "roles": ['quote_slide', 'callout', 'section_divider', 'side_panel', 'badge'],
    "anchor_names": ['quote', 'callout', 'side_panel', 'chapter_card', 'badge'],
    "anchor_name_regex": '^(quote|callout|side_panel|chapter_card|badge)$',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 60, 'min': 0, 'max': 400}, 'rotate_duration_ms': {'default': 900, 'min': 600, 'max': 1500}, 'fade_duration_ms': {'default': 550, 'min': 350, 'max': 900}, 'from_deg': {'default': -10, 'min': -18, 'max': 18}, 'settle_duration_ms': {'default': 320, 'min': 200, 'max': 500}, 'settle_to_pct': {'default': 103, 'min': 101, 'max': 106}}

TAGS = ['pivot', 'editorial', 'card', 'magazine', 'refined']
INTENSITY = 5
EMBEDDING_TEXT = (
    'A poised transition that feels like a printed card or quote panel hinging into place. The element rotates in with a short dissolve, then gets a restrained scale reaffirmation so the end state feels locked and deliberate. It works beautifully for pull quotes, sidebars, chapter cards, badges, and compact callout panels. The aesthetic is editorial, tactile, and more design-forward than a standard rotate-in.'
)
CONTENT_MATCHERS = {'is_quote': True, 'is_panel': True, 'short_text': True, 'has_badge_or_kicker': True}
COMPLEMENTARY_WITH = ['headline_restrike_focus', 'seal_tilt_reaffirm', 'numeric_confidence_bump']
CONFLICTS_WITH = ['rotate_in', 'badge_swing_in']


MOOD = ['editorial', 'cinematic', 'calm', 'restrained']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_rotate_in, emit_grow_emphasis
    _delay = int(p.get('delay_ms', 60))
    _rotate_ms = int(p.get('rotate_duration_ms', 900))
    _fade_ms = int(p.get('fade_duration_ms', 550))
    _from_deg = int(p.get('from_deg', -10))
    _settle_ms = int(p.get('settle_duration_ms', 320))
    _settle_to = int(p.get('settle_to_pct', 103))
    emit_fade_in(slide, target_shape, delay_ms=_delay, duration_ms=_fade_ms)
    emit_rotate_in(slide, target_shape, delay_ms=_delay, duration_ms=_rotate_ms, from_deg=_from_deg)
    emit_grow_emphasis(slide, target_shape, delay_ms=_delay + max(_rotate_ms, _fade_ms), duration_ms=_settle_ms, to_pct=_settle_to)
