"""Auto-distilled motion skill: icon_orbit_tap.

Icons and small illustrations get a compact orbital tug with a soft closing tap.

Category: emphasis. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'icon_orbit_tap'
CATEGORY = 'emphasis'
DESCRIPTION = 'Icons and small illustrations get a compact orbital tug with a soft closing tap.'

APPLICABILITY = {
    "roles": ['icon', 'feature_tile', 'process_step', 'badge', 'illustration_spot'],
    "anchor_names": ['icon', 'illustration', 'symbol', 'glyph', 'step', 'marker'],
    "anchor_name_regex": '(icon|illustration|symbol|glyph|step|marker)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 130, 'min': 0, 'max': 1200}, 'duration_ms': {'default': 520, 'min': 360, 'max': 820}, 'dx_frac': {'default': 0.03, 'min': 0.015, 'max': 0.06}, 'dy_frac': {'default': -0.02, 'min': -0.05, 'max': 0.02}, 'bow_frac': {'default': 0.18, 'min': 0.08, 'max': 0.3}, 'pulse_pct': {'default': 104, 'min': 102, 'max': 108}}

TAGS = ['iconic', 'curved', 'playful', 'compact', 'accent']
INTENSITY = 5
EMBEDDING_TEXT = (
    'This effect gives icons and compact graphics a quick orbital tug, as if they briefly circle a focal point and snap back into place. The curve adds personality without turning into a full playful bounce, so it feels crisp and product-polished. It is excellent for feature icons, process markers, and small spot illustrations that need a visual tap. The finish is softened by a modest pulse, keeping the motion friendly and intentional.'
)
CONTENT_MATCHERS = {'has_icon': True, 'small_shape': True, 'digits': False, 'is_headline': False, 'is_metric': False}
COMPLEMENTARY_WITH = ['breathing_halo', 'panel_unveil_settle']
CONFLICTS_WITH = ['orbital_accent', 'soft_arc_settle']


MOOD = ['punchy', 'playful', 'editorial']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_arc_path, emit_pulse
    base_delay = int(p.get('delay_ms', 130))
    base_dur = int(p.get('duration_ms', 520))
    dx = float(p.get('dx_frac', 0.03))
    dy = float(p.get('dy_frac', -0.02))
    bow = float(p.get('bow_frac', 0.18))
    pulse_to = int(p.get('pulse_pct', 104))
    half = max(180, base_dur // 2)
    emit_arc_path(slide, target_shape, delay_ms=base_delay, duration_ms=half, dx_frac=dx, dy_frac=dy, bow_frac=bow)
    emit_arc_path(slide, target_shape, delay_ms=base_delay + half, duration_ms=half, dx_frac=-dx, dy_frac=-dy, bow_frac=-bow)
    emit_pulse(slide, target_shape, delay_ms=base_delay + base_dur - 120, duration_ms=220, scale_pct=pulse_to, repeats=1)
