"""Auto-distilled motion skill: lateral_handoff_crossfade.

A long right-to-left handoff sweep with a subtle settle pulse for panels and screenshots.

Category: transition. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'lateral_handoff_crossfade'
CATEGORY = 'transition'
DESCRIPTION = 'A long right-to-left handoff sweep with a subtle settle pulse for panels and screenshots.'

APPLICABILITY = {
    "roles": ['comparison', 'product_showcase', 'feature_panel', 'before_after', 'dashboard'],
    "anchor_names": ['panel', 'card', 'comparison', 'product_shot', 'screenshot'],
    "anchor_name_regex": '^(panel|card|comparison|product_shot|screenshot)$',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 500}, 'fly_duration_ms': {'default': 1150, 'min': 700, 'max': 1700}, 'fade_duration_ms': {'default': 650, 'min': 400, 'max': 900}, 'settle_duration_ms': {'default': 380, 'min': 250, 'max': 650}, 'settle_scale_pct': {'default': 103, 'min': 101, 'max': 106}}

TAGS = ['sweeping', 'panel', 'product', 'confident', 'handoff']
INTENSITY = 6
EMBEDDING_TEXT = (
    'This transition feels like one scene handing off to the next with a confident lateral sweep. The shape flies in from the right while dissolving, then lands with a tiny settle pulse that makes product cards and comparison panels feel intentional. It is ideal for dashboards, screenshots, before-and-after layouts, and multi-panel storytelling where continuity matters. The look is modern, polished, and slightly more energetic than a plain slide-in.'
)
CONTENT_MATCHERS = {'is_panel': True, 'has_image': True, 'comparative_layout': True, 'medium_text_density': True}
COMPLEMENTARY_WITH = ['bullet_stagger_reveal', 'chart_peak_ping', 'count_up_metric']
CONFLICTS_WITH = ['slide_in_left', 'panel_unveil_settle']


MOOD = ['editorial', 'calm', 'cinematic']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_fly_in, emit_pulse
    _delay = int(p.get('delay_ms', 120))
    _fly_ms = int(p.get('fly_duration_ms', 1150))
    _fade_ms = int(p.get('fade_duration_ms', 650))
    _settle_ms = int(p.get('settle_duration_ms', 380))
    _scale = int(p.get('settle_scale_pct', 103))
    emit_fade_in(slide, target_shape, delay_ms=_delay, duration_ms=_fade_ms)
    emit_fly_in(slide, target_shape, direction='right', delay_ms=_delay, duration_ms=_fly_ms)
    emit_pulse(slide, target_shape, delay_ms=_delay + max(_fly_ms, _fade_ms), duration_ms=_settle_ms, scale_pct=_scale, repeats=1)
