"""Auto-distilled motion skill: logo_swoop_resolve.

A logo or seal glides in on a curved path while rotating into alignment and fading up.

Category: composite. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'logo_swoop_resolve'
CATEGORY = 'composite'
DESCRIPTION = 'A logo or seal glides in on a curved path while rotating into alignment and fading up.'

APPLICABILITY = {
    "roles": ['cover', 'brand_mark', 'section_divider', 'closing'],
    "anchor_names": ['logo', 'brand', 'mark', 'seal', 'badge'],
    "anchor_name_regex": '(logo|brand|mark|seal|badge)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 1000}, 'fade_duration_ms': {'default': 420, 'min': 250, 'max': 700}, 'rotate_duration_ms': {'default': 600, 'min': 400, 'max': 1000}, 'travel_duration_ms': {'default': 760, 'min': 500, 'max': 1200}, 'from_deg': {'default': -22, 'min': -90, 'max': 90}, 'dx_frac': {'default': -0.04, 'min': -0.18, 'max': 0.18}, 'dy_frac': {'default': -0.03, 'min': -0.12, 'max': 0.08}, 'bow_frac': {'default': 0.12, 'min': -0.1, 'max': 0.3}}

TAGS = ['brand', 'premium', 'resolved', 'sleek', 'ceremonial']
INTENSITY = 5
EMBEDDING_TEXT = (
    'A polished brand-mark entrance for logos, seals, and small iconic marks that deserve a ceremonial reveal. The element fades up, sweeps along a curved path, and rotates gently into final alignment, creating a resolved, premium finish rather than a playful spin. It retrieves well for cover slides, section openers, sponsorship marks, and closing frames with restrained brand presence. Medium intensity with elegant motion and strong design-system compatibility.'
)
CONTENT_MATCHERS = {'is_logo_like': True, 'short_text': True, 'has_icon': True, 'is_decorative_mark': True}
COMPLEMENTARY_WITH = ['headline_arc_settle', 'glass_crossfade_settle', 'focus_pull_dissolve']
CONFLICTS_WITH = ['badge_pinwheel_pop', 'seal_twirl_land', 'morph_anchor_arc']


MOOD = ['editorial', 'cinematic']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_rotate_in, emit_arc_path
    delay = int(p.get('delay_ms', 80))
    emit_fade_in(slide, target_shape, delay_ms=delay, duration_ms=int(p.get('fade_duration_ms', 420)))
    emit_rotate_in(slide, target_shape, delay_ms=delay, duration_ms=int(p.get('rotate_duration_ms', 600)), from_deg=int(p.get('from_deg', -22)))
    emit_arc_path(slide, target_shape, delay_ms=delay, duration_ms=int(p.get('travel_duration_ms', 760)), dx_frac=float(p.get('dx_frac', -0.04)), dy_frac=float(p.get('dy_frac', -0.03)), bow_frac=float(p.get('bow_frac', 0.12)))
