"""Auto-distilled motion skill: metric_snap_pop.

Fast grow-in with a crisp finishing pulse for KPI numbers, deltas, and scorecards.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'metric_snap_pop'
CATEGORY = 'entrance'
DESCRIPTION = 'Fast grow-in with a crisp finishing pulse for KPI numbers, deltas, and scorecards.'

APPLICABILITY = {
    "roles": ['hero_giant_metric', 'kpi', 'scorecard', 'comparison', 'dashboard'],
    "anchor_names": ['metric', 'number', 'stat', 'delta', 'kpi'],
    "anchor_name_regex": '(metric|number|stat|delta|kpi)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 60, 'min': 0, 'max': 400}, 'duration_ms': {'default': 520, 'min': 400, 'max': 800}, 'from_pct': {'default': 82, 'min': 60, 'max': 95}, 'pulse_duration_ms': {'default': 280, 'min': 180, 'max': 500}, 'scale_pct': {'default': 106, 'min': 102, 'max': 112}}

TAGS = ['numeric', 'confident', 'snappy', 'clean', 'data']
INTENSITY = 6
EMBEDDING_TEXT = (
    'This motion gives large numbers a clean snap-in followed by a restrained pulse that says the value matters. It is ideal for giant metrics, dashboard stats, deltas, and scoreboard callouts where speed and clarity are more important than drama. The aesthetic is crisp, modern, and high-confidence, with enough energy to spotlight digits without becoming playful or noisy.'
)
CONTENT_MATCHERS = {'digits': True, 'is_metric': True, 'short_text': True, 'is_headline': False}
COMPLEMENTARY_WITH = ['count_up_metric']
CONFLICTS_WITH = ['pulse_emphasis', 'zoom_from_center']


MOOD = ['technical', 'boardroom', 'punchy', 'playful']
ARCHETYPE_FIT = ['data', 'boardroom']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_grow_from_small, emit_pulse
    emit_grow_from_small(slide, target_shape,
                         delay_ms=int(p.get('delay_ms', 60)),
                         duration_ms=int(p.get('duration_ms', 520)),
                         from_pct=int(p.get('from_pct', 82)))
    emit_pulse(slide, target_shape,
               delay_ms=int(p.get('delay_ms', 60)) + int(p.get('duration_ms', 520)),
               duration_ms=int(p.get('pulse_duration_ms', 280)),
               scale_pct=int(p.get('scale_pct', 106)),
               repeats=1)
