"""Auto-distilled motion skill: metric_snap_focus.

Brisk KPI pop-in with a tiny follow-up pulse that makes a number feel important.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'metric_snap_focus'
CATEGORY = 'entrance'
DESCRIPTION = 'Brisk KPI pop-in with a tiny follow-up pulse that makes a number feel important.'

APPLICABILITY = {
    "roles": ['hero_giant_metric', 'dashboard', 'scorecard', 'kpi_callout'],
    "anchor_names": ['metric', 'kpi', 'value', 'number', 'stat'],
    "anchor_name_regex": '(?i)(metric|kpi|value|number|stat)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 900}, 'duration_ms': {'default': 540, 'min': 420, 'max': 800}, 'from_pct': {'default': 74, 'min': 60, 'max': 92}, 'pulse_duration_ms': {'default': 320, 'min': 220, 'max': 500}, 'pulse_scale_pct': {'default': 106, 'min': 102, 'max': 110}}

TAGS = ['kpi', 'numeric', 'snappy', 'focused', 'clean']
INTENSITY = 6
EMBEDDING_TEXT = (
    'A big number snaps in from slightly undersized, then gives one restrained pulse to lock attention onto the metric. It is ideal for ARR, growth, conversion, savings, and any hero statistic that should feel decisive without becoming gimmicky. The timing is short and punchy, so dashboards and investor slides gain urgency and clarity. This is a higher-energy entrance than a plain zoom, but still controlled and presentation-safe.'
)
CONTENT_MATCHERS = {'digits': True, 'is_headline': False, 'short_text': True, 'is_kpi': True, 'has_image': False}
COMPLEMENTARY_WITH = ['chart_bar_grow', 'count_up_metric']
CONFLICTS_WITH = ['pulse_emphasis', 'zoom_from_center', 'dramatic_zoom']


MOOD = ['technical', 'boardroom', 'punchy', 'editorial']
ARCHETYPE_FIT = ['data', 'boardroom']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_grow_from_small, emit_pulse
    base = int(p.get('delay_ms', 80))
    main = int(p.get('duration_ms', 540))
    emit_grow_from_small(slide, target_shape, delay_ms=base, duration_ms=main, from_pct=int(p.get('from_pct', 74)))
    emit_pulse(slide, target_shape, delay_ms=base + main, duration_ms=int(p.get('pulse_duration_ms', 320)), scale_pct=int(p.get('pulse_scale_pct', 106)), repeats=1)
