"""Auto-distilled motion skill: metric_digit_spark.

Fast numeric text reveal with tight digit stagger, small zoom-in, and a sharp finishing pulse.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'metric_digit_spark'
CATEGORY = 'text'
DESCRIPTION = 'Fast numeric text reveal with tight digit stagger, small zoom-in, and a sharp finishing pulse.'

APPLICABILITY = {
    "roles": ['hero_giant_metric', 'dashboard', 'data_callout', 'comparison'],
    "anchor_names": ['metric', 'big_number', 'stat', 'kpi', 'value'],
    "anchor_name_regex": '(?i)(metric|big[_ ]?number|stat|kpi|value)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 400}, 'in_duration_ms': {'default': 480, 'min': 350, 'max': 700}, 'from_pct': {'default': 94, 'min': 88, 'max': 98}, 'text_offset_ms': {'default': 60, 'min': 0, 'max': 180}, 'stagger_ms': {'default': 24, 'min': 10, 'max': 60}, 'per_duration_ms': {'default': 160, 'min': 120, 'max': 220}, 'pulse_gap_ms': {'default': 80, 'min': 0, 'max': 180}, 'pulse_duration_ms': {'default': 360, 'min': 280, 'max': 600}, 'pulse_scale_pct': {'default': 108, 'min': 104, 'max': 112}}

TAGS = ['metric', 'digits', 'snappy', 'analytic', 'precise']
INTENSITY = 6
EMBEDDING_TEXT = (
    'A compact, data-first text motion designed for KPIs, revenue figures, percentages, and hero metrics. The number arrives with a restrained zoom, the digits tick in quickly, and then the whole figure lands with a single pulse for emphasis. It feels sharp and product-like rather than playful. Use it when a number must read instantly and still feel important.'
)
CONTENT_MATCHERS = {'digits': True, 'metric_like': True, 'short_text': True}
COMPLEMENTARY_WITH = ['background_parallax_glide', 'hero_metric_heartbeat_loop', 'chart_peak_ping']
CONFLICTS_WITH = ['count_up_metric', 'metric_snap_pop', 'numeric_confidence_bump']


MOOD = ['boardroom', 'technical', 'punchy', 'editorial']
ARCHETYPE_FIT = ['data', 'boardroom']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_zoom_in, emit_text_stagger, emit_pulse
    base_delay = int(p.get('delay_ms', 0))
    in_duration_ms = int(p.get('in_duration_ms', 480))
    from_pct = int(p.get('from_pct', 94))
    text_offset_ms = int(p.get('text_offset_ms', 60))
    stagger_ms = int(p.get('stagger_ms', 24))
    per_duration_ms = int(p.get('per_duration_ms', 160))
    pulse_gap_ms = int(p.get('pulse_gap_ms', 80))
    pulse_duration_ms = int(p.get('pulse_duration_ms', 360))
    pulse_scale_pct = int(p.get('pulse_scale_pct', 108))
    emit_zoom_in(slide, target_shape, delay_ms=base_delay, duration_ms=in_duration_ms, from_pct=from_pct)
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + text_offset_ms, stagger_ms=stagger_ms, per_duration_ms=per_duration_ms)
    emit_pulse(slide, target_shape, delay_ms=base_delay + in_duration_ms + pulse_gap_ms, duration_ms=pulse_duration_ms, scale_pct=pulse_scale_pct, repeats=1)
