"""Auto-distilled motion skill: metric_digit_pop_stagger.

Numerical text lands crisply, then resolves with a precise stagger and a light pulse.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'metric_digit_pop_stagger'
CATEGORY = 'text'
DESCRIPTION = 'Numerical text lands crisply, then resolves with a precise stagger and a light pulse.'

APPLICABILITY = {
    "roles": ['hero_giant_metric', 'kpi', 'scorecard', 'dashboard_stat'],
    "anchor_names": ['metric', 'value', 'number', 'stat'],
    "anchor_name_regex": '^(metric|value|number|stat)$',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 1000}, 'zoom_duration_ms': {'default': 360, 'min': 240, 'max': 640}, 'from_pct': {'default': 88, 'min': 70, 'max': 95}, 'stagger_ms': {'default': 28, 'min': 10, 'max': 80}, 'per_duration_ms': {'default': 260, 'min': 150, 'max': 480}, 'pulse_duration_ms': {'default': 320, 'min': 220, 'max': 700}, 'pulse_scale_pct': {'default': 106, 'min': 102, 'max': 112}}

TAGS = ['metric', 'numeric', 'crisp', 'kpi', 'precise']
INTENSITY = 6
EMBEDDING_TEXT = (
    'This is a sharp metric treatment for big numbers, KPIs, percentages, and scorecards. The text zooms in with a compact snap, the characters or words resolve in a fast stagger, and a restrained pulse gives the value a final moment of emphasis. It reads as data-forward, confident, and polished rather than playful. Choose it when digits are the message and the slide needs a high-clarity focal point.'
)
CONTENT_MATCHERS = {'digits': True, 'is_metric': True, 'short_text': True}
COMPLEMENTARY_WITH = ['count_up_metric', 'chart_bar_grow']
CONFLICTS_WITH = ['metric_snap_focus', 'pulse_emphasis']


MOOD = ['boardroom', 'technical', 'editorial', 'punchy']
ARCHETYPE_FIT = ['data', 'boardroom']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_zoom_in, emit_text_stagger, emit_pulse
    base_delay = int(p.get('delay_ms', 0))
    zoom_dur = int(p.get('zoom_duration_ms', 360))
    stagger = int(p.get('stagger_ms', 28))
    per_dur = int(p.get('per_duration_ms', 260))
    emit_zoom_in(slide, target_shape, delay_ms=base_delay, duration_ms=zoom_dur, from_pct=int(p.get('from_pct', 88)))
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + 60, stagger_ms=stagger, per_duration_ms=per_dur)
    emit_pulse(slide, target_shape, delay_ms=base_delay + zoom_dur + 140, duration_ms=int(p.get('pulse_duration_ms', 320)), scale_pct=int(p.get('pulse_scale_pct', 106)), repeats=1)
