"""Auto-distilled motion skill: metric_bloom_echo.

A KPI or big number zooms in cleanly, then confirms itself with a restrained echo pulse.

Category: composite. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'metric_bloom_echo'
CATEGORY = 'composite'
DESCRIPTION = 'A KPI or big number zooms in cleanly, then confirms itself with a restrained echo pulse.'

APPLICABILITY = {
    "roles": ['hero_giant_metric', 'kpi', 'stat_callout', 'scorecard'],
    "anchor_names": ['metric', 'value', 'number', 'stat', 'kpi'],
    "anchor_name_regex": '(metric|value|number|stat|kpi|total|amount)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 1200}, 'zoom_duration_ms': {'default': 560, 'min': 400, 'max': 900}, 'from_pct': {'default': 72, 'min': 45, 'max': 90}, 'echo_delay_ms': {'default': 60, 'min': 0, 'max': 220}, 'pulse_duration_ms': {'default': 340, 'min': 250, 'max': 700}, 'scale_pct': {'default': 107, 'min': 103, 'max': 115}}

TAGS = ['numeric', 'confident', 'clean', 'modern', 'high-signal']
INTENSITY = 6
EMBEDDING_TEXT = (
    'A crisp metric entrance for KPI tiles, hero numbers, and short numeric callouts. The figure blooms up from a smaller scale, lands cleanly, then gives a restrained echo pulse that feels confident rather than flashy. It is a strong retrieval match for dashboards, revenue stats, growth percentages, scorecards, and slides dominated by digits. Medium intensity with polished keynote energy and clear emphasis on importance.'
)
CONTENT_MATCHERS = {'digits': True, 'short_text': True, 'is_metric': True, 'is_headline': False}
COMPLEMENTARY_WITH = ['bullet_stagger_reveal', 'photo_wipe_drift', 'focus_pull_dissolve']
CONFLICTS_WITH = ['count_up_metric', 'metric_snap_focus', 'dramatic_zoom']


MOOD = ['boardroom', 'technical', 'editorial', 'warm']
ARCHETYPE_FIT = ['data', 'boardroom', 'brand', 'narrative']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_zoom_in, emit_pulse
    delay = int(p.get('delay_ms', 120))
    zoom_dur = int(p.get('zoom_duration_ms', 560))
    emit_zoom_in(slide, target_shape, delay_ms=delay, duration_ms=zoom_dur, from_pct=int(p.get('from_pct', 72)))
    emit_pulse(slide, target_shape, delay_ms=delay + zoom_dur + int(p.get('echo_delay_ms', 60)), duration_ms=int(p.get('pulse_duration_ms', 340)), scale_pct=int(p.get('scale_pct', 107)), repeats=1)
