"""Auto-distilled motion skill: milestone_stamp_confirm.

Small nodes or milestones stamp into place with a compact rotate-pop confirmation.

Category: composite. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'milestone_stamp_confirm'
CATEGORY = 'composite'
DESCRIPTION = 'Small nodes or milestones stamp into place with a compact rotate-pop confirmation.'

APPLICABILITY = {
    "roles": ['timeline_milestone', 'process_node', 'roadmap_marker', 'agenda_marker'],
    "anchor_names": ['marker', 'milestone', 'node', 'step', 'pin', 'badge'],
    "anchor_name_regex": '(?i)(marker|milestone|node|step|pin|checkpoint|badge|dot)',
    "max_per_slide": 3,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 800}, 'duration_ms': {'default': 520, 'min': 420, 'max': 800}, 'from_pct': {'default': 72, 'min': 60, 'max': 84}, 'from_deg': {'default': -10, 'min': -20, 'max': 20}, 'pulse_ms': {'default': 240, 'min': 200, 'max': 360}, 'pulse_pct': {'default': 107, 'min': 104, 'max': 110}}

TAGS = ['marker', 'timeline', 'process', 'compact', 'affirming']
INTENSITY = 7
EMBEDDING_TEXT = (
    'A compact composite entrance for roadmap dots, process nodes, agenda markers, and timeline milestones. The shape grows from small size while rotating in slightly, then finishes with a short confirmation pulse that feels like a stamped decision point. Use it for step indicators, pinned highlights, map points, and progress markers that need to read as deliberate and active. The motion is punchy, precise, and more assertive than a simple fade or bounce.'
)
CONTENT_MATCHERS = {'small_shape': True, 'icon_like': True, 'is_marker': True, 'step_or_sequence': True}
COMPLEMENTARY_WITH = ['agenda_marker_sweep', 'orbital_accent']
CONFLICTS_WITH = ['badge_swing_in', 'bounce_in', 'rotate_in']


MOOD = ['bold', 'punchy']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_grow_from_small, emit_rotate_in, emit_pulse
    delay = int(p.get('delay_ms', 80))
    duration = int(p.get('duration_ms', 520))
    from_pct = int(p.get('from_pct', 72))
    from_deg = int(p.get('from_deg', -10))
    pulse_ms = int(p.get('pulse_ms', 240))
    pulse_pct = int(p.get('pulse_pct', 107))
    emit_grow_from_small(slide, target_shape, delay_ms=delay, duration_ms=duration, from_pct=from_pct)
    emit_rotate_in(slide, target_shape, delay_ms=delay, duration_ms=duration, from_deg=from_deg)
    emit_pulse(slide, target_shape, delay_ms=delay + duration, duration_ms=pulse_ms, scale_pct=pulse_pct, repeats=1)
