"""Auto-distilled motion skill: numeric_confidence_bump.

KPI figures swell with a clean overshoot, then settle into a confident micro-pulse.

Category: emphasis. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'numeric_confidence_bump'
CATEGORY = 'emphasis'
DESCRIPTION = 'KPI figures swell with a clean overshoot, then settle into a confident micro-pulse.'

APPLICABILITY = {
    "roles": ['hero_giant_metric', 'kpi_card', 'scoreboard', 'pricing_stat', 'dashboard'],
    "anchor_names": ['metric', 'number', 'value', 'percent', 'delta', 'total', 'stat'],
    "anchor_name_regex": '(metric|number|value|percent|delta|total|stat)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 1200}, 'duration_ms': {'default': 360, 'min': 240, 'max': 700}, 'grow_to_pct': {'default': 114, 'min': 105, 'max': 125}, 'pulse_pct': {'default': 106, 'min': 102, 'max': 112}}

TAGS = ['crisp', 'data', 'confident', 'modern', 'clean']
INTENSITY = 5
EMBEDDING_TEXT = (
    'This emphasis is tuned for numbers, percentages, and single-line KPI readouts that need a moment of authority. It feels like a polished confidence bump: a quick overshoot in scale followed by a restrained settling pulse. The look is modern, product-demo friendly, and especially strong on dashboard cards, pricing stats, and performance deltas. Intensity is medium, so it reads premium rather than playful.'
)
CONTENT_MATCHERS = {'digits': True, 'is_metric': True, 'short_text': True, 'is_headline': False, 'has_icon': False}
COMPLEMENTARY_WITH = ['chart_bar_grow', 'bullet_stagger_reveal']
CONFLICTS_WITH = ['metric_snap_pop', 'pulse_emphasis']


MOOD = ['boardroom', 'technical', 'editorial', 'punchy']
ARCHETYPE_FIT = ['data', 'boardroom']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_grow_emphasis, emit_pulse
    base_delay = int(p.get('delay_ms', 120))
    base_dur = int(p.get('duration_ms', 360))
    grow_to = int(p.get('grow_to_pct', 114))
    pulse_to = int(p.get('pulse_pct', 106))
    emit_grow_emphasis(slide, target_shape, delay_ms=base_delay, duration_ms=base_dur, to_pct=grow_to)
    emit_pulse(slide, target_shape, delay_ms=base_delay + max(120, base_dur - 120), duration_ms=min(260, max(180, base_dur - 80)), scale_pct=pulse_to, repeats=1)
