"""Auto-distilled motion skill: page_hinge_drop.

Top-down page-turn arrival with a light hinge rotation for chapter titles, tabs, and side labels.

Category: transition. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'page_hinge_drop'
CATEGORY = 'transition'
DESCRIPTION = 'Top-down page-turn arrival with a light hinge rotation for chapter titles, tabs, and side labels.'

APPLICABILITY = {
    "roles": ['section_divider', 'sidebar_callout', 'eyebrow_label', 'agenda_step', 'chapter_header'],
    "anchor_names": ['section_title', 'eyebrow', 'sidebar', 'label', 'tab'],
    "anchor_name_regex": '(section|eyebrow|sidebar|label|tab|chapter)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 500}, 'duration_ms': {'default': 920, 'min': 700, 'max': 1400}, 'from_deg': {'default': 10, 'min': 4, 'max': 18}}

TAGS = ['chapter', 'hinge', 'directional', 'structured', 'editorial']
INTENSITY = 5
EMBEDDING_TEXT = (
    'This transition feels like a page or tab dropping into place from above, with just enough hinge rotation to add directional character. It is strongest on compact labels, chapter headers, eyebrow text, and sidebar modules that benefit from a crisp top-origin movement. The style is editorial and structured, not whimsical. Use it when the content is short, categorical, or functioning as a navigation-like divider.'
)
CONTENT_MATCHERS = {'is_section_title': True, 'few_words': True, 'narrow_shape': True, 'digits': False}
COMPLEMENTARY_WITH = ['headline_word_cascade', 'bullet_stagger_reveal']
CONFLICTS_WITH = ['rotate_in', 'badge_swing_in', 'seal_twirl_land']


MOOD = ['cinematic', 'editorial', 'calm']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_rotate_in, emit_fly_in
    _delay = int(p.get('delay_ms', 0))
    _duration = int(p.get('duration_ms', 920))
    _deg = int(p.get('from_deg', 10))
    emit_fly_in(slide, target_shape, direction='top', delay_ms=_delay, duration_ms=_duration)
    emit_rotate_in(slide, target_shape, delay_ms=_delay, duration_ms=_duration, from_deg=_deg)
