"""Auto-distilled motion skill: panel_unveil_settle.

Directional wipe with a tiny settle, tuned for screenshots, tables, and UI panels.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'panel_unveil_settle'
CATEGORY = 'entrance'
DESCRIPTION = 'Directional wipe with a tiny settle, tuned for screenshots, tables, and UI panels.'

APPLICABILITY = {
    "roles": ['product_screenshot', 'dashboard_panel', 'table', 'comparison', 'ui_mockup'],
    "anchor_names": ['visual', 'screenshot', 'panel', 'table', 'mockup'],
    "anchor_name_regex": '(visual|screenshot|panel|table|mockup)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 100, 'min': 0, 'max': 500}, 'wipe_duration_ms': {'default': 760, 'min': 500, 'max': 1100}, 'settle_duration_ms': {'default': 220, 'min': 150, 'max': 400}, 'to_pct': {'default': 102, 'min': 101, 'max': 105}}

TAGS = ['product', 'ui', 'unveil', 'structured', 'controlled']
INTENSITY = 4
EMBEDDING_TEXT = (
    'This entrance behaves like a product panel being unveiled from the edge, then locking into place with a tiny settle. It works especially well for screenshots, dashboards, tables, and app mockups because the wipe reinforces rectangular geometry and clean structure. The feeling is precise, product-led, and slightly theatrical without crossing into a flashy transition.'
)
CONTENT_MATCHERS = {'is_table': True, 'is_screenshot': True, 'large_visual': True, 'digits': False}
COMPLEMENTARY_WITH = ['image_ken_burns', 'bullet_stagger_reveal']
CONFLICTS_WITH = ['editorial_wipe_rise']


MOOD = ['editorial', 'calm']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_grow_emphasis
    emit_wipe_in(slide, target_shape,
                 direction='left',
                 delay_ms=int(p.get('delay_ms', 100)),
                 duration_ms=int(p.get('wipe_duration_ms', 760)))
    emit_grow_emphasis(slide, target_shape,
                       delay_ms=int(p.get('delay_ms', 100)) + int(p.get('wipe_duration_ms', 760)),
                       duration_ms=int(p.get('settle_duration_ms', 220)),
                       to_pct=int(p.get('to_pct', 102)))
