"""Auto-distilled motion skill: panel_shutter_unfold.

Structured shutter reveal for cards, screenshots, and dashboard panels.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'panel_shutter_unfold'
CATEGORY = 'entrance'
DESCRIPTION = 'Structured shutter reveal for cards, screenshots, and dashboard panels.'

APPLICABILITY = {
    "roles": ['content_card', 'feature_card', 'comparison_panel', 'screenshot', 'dashboard'],
    "anchor_names": ['card', 'panel', 'screenshot', 'module', 'callout'],
    "anchor_name_regex": '(?i)(card|panel|screenshot|module|callout|window|dashboard)',
    "max_per_slide": 3,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 1200}, 'wipe_duration_ms': {'default': 620, 'min': 400, 'max': 900}, 'grow_duration_ms': {'default': 560, 'min': 400, 'max': 800}, 'from_pct': {'default': 94, 'min': 88, 'max': 99}}

TAGS = ['structured', 'crisp', 'ui', 'reveal', 'rectangular']
INTENSITY = 5
EMBEDDING_TEXT = (
    'A panel appears as if a clean shutter is opening while the surface gently firms into place. The effect feels especially good on UI cards, screenshots, comparison panels, and dashboard modules because it respects rectangular geometry. It reads as precise, organized, and modern rather than playful. Search terms that fit are card reveal, dashboard panel entrance, screenshot unfold, and structured wipe-in.'
)
CONTENT_MATCHERS = {'is_rectangular': True, 'has_image': True, 'is_card_like': True}
COMPLEMENTARY_WITH = ['card_rise_settle', 'photo_wipe_drift']
CONFLICTS_WITH = ['grow_reveal', 'editorial_wipe_rise']


MOOD = ['editorial', 'cinematic']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_grow_from_small
    d = int(p.get('delay_ms', 80))
    wd = int(p.get('wipe_duration_ms', 620))
    gd = int(p.get('grow_duration_ms', 560))
    fp = int(p.get('from_pct', 94))
    emit_wipe_in(slide, target_shape, direction='left', delay_ms=d, duration_ms=wd)
    emit_grow_from_small(slide, target_shape, delay_ms=d + 30, duration_ms=gd, from_pct=fp)
