"""Auto-distilled motion skill: photo_wipe_drift.

Cinematic image reveal with a directional wipe while the visual drifts into final framing.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'photo_wipe_drift'
CATEGORY = 'entrance'
DESCRIPTION = 'Cinematic image reveal with a directional wipe while the visual drifts into final framing.'

APPLICABILITY = {
    "roles": ['cover', 'image_feature', 'product_hero', 'case_study'],
    "anchor_names": ['hero_image', 'image', 'photo', 'product_shot'],
    "anchor_name_regex": '(?i)(image|photo|hero_image|product)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 1000}, 'duration_ms': {'default': 960, 'min': 700, 'max': 1200}, 'dx_frac': {'default': 0.05, 'min': 0.02, 'max': 0.08}, 'dy_frac': {'default': 0.0, 'min': -0.03, 'max': 0.03}, 'bow_frac': {'default': -0.03, 'min': -0.08, 'max': 0.02}}

TAGS = ['image', 'cinematic', 'editorial', 'smooth', 'premium']
INTENSITY = 5
EMBEDDING_TEXT = (
    'A photo wipes on while simultaneously drifting a few pixels into place, creating a subtle parallax-style entrance. This aesthetic suits hero photography, product renders, lifestyle images, and polished case-study visuals where the frame should feel alive. The motion is smooth and cinematic rather than loud, with enough movement to feel expensive without distracting from captions or headlines. Use it on large visuals that deserve a premium reveal.'
)
CONTENT_MATCHERS = {'has_image': True, 'large_visual': True, 'is_headline': False, 'digits': False, 'multi_line_text': False}
COMPLEMENTARY_WITH = ['headline_arc_settle', 'subhead_stagger_fade']
CONFLICTS_WITH = ['image_ken_burns', 'editorial_wipe_rise']


MOOD = ['editorial', 'cinematic', 'calm']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_arc_path
    base = int(p.get('delay_ms', 120))
    main = int(p.get('duration_ms', 960))
    emit_wipe_in(slide, target_shape, direction='left', delay_ms=base, duration_ms=main)
    emit_arc_path(slide, target_shape, delay_ms=base, duration_ms=main, dx_frac=float(p.get('dx_frac', 0.05)), dy_frac=float(p.get('dy_frac', 0.0)), bow_frac=float(p.get('bow_frac', -0.03)))
