"""Auto-distilled motion skill: planet_orbit_idle.

Tiny self-orbit loop that gives icons and decorative accents a celestial idle motion.

Category: ambient. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'planet_orbit_idle'
CATEGORY = 'ambient'
DESCRIPTION = 'Tiny self-orbit loop that gives icons and decorative accents a celestial idle motion.'

APPLICABILITY = {
    "roles": ['icon_cluster', 'feature_grid', 'decorative_accent', 'cover'],
    "anchor_names": ['icon', 'accent', 'dot', 'spark'],
    "anchor_name_regex": '.*(icon|accent|spark|dot).*',
    "max_per_slide": 2,
}

PARAMETERS = {'radius_in': {'default': 0.12, 'min': 0.06, 'max': 0.4}, 'duration_ms': {'default': 7000, 'min': 4000, 'max': 10000}}

TAGS = ['playful', 'celestial', 'decorative', 'lightweight', 'ambient']
INTENSITY = 4
EMBEDDING_TEXT = (
    "This creates a small orbital loop around the shape's starting position, making icons and tiny accents feel like satellites in a clean system. It is ideal for decorative sparks, simple feature icons, and lightweight visual garnish on cover or product ecosystem slides. The motion feels playful and spatial without becoming noisy because the radius stays small and the timing stays slow. Use it for nonessential accent shapes, not for core reading content or dense UI screenshots."
)
CONTENT_MATCHERS = {'is_icon': True, 'is_decorative': True, 'small_shape': True}
COMPLEMENTARY_WITH = ['soft_arc_settle', 'gentle_rise_fade']
CONFLICTS_WITH = ['orbital_accent', 'icon_orbit_tap']


MOOD = ['calm', 'editorial', 'playful', 'punchy']
ARCHETYPE_FIT = ['brand', 'narrative', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _shell_helpers import add_orbital_motion
    center_x_in = (float(target_shape.left) + float(target_shape.width) / 2.0) / 914400.0
    center_y_in = (float(target_shape.top) + float(target_shape.height) / 2.0) / 914400.0
    add_orbital_motion(
        slide,
        target_shape,
        center_xy=(center_x_in, center_y_in),
        radius_in=float(p.get('radius_in', 0.12)),
        duration_ms=int(p.get('duration_ms', 7000)),
        direction='counterclockwise',
    )
