"""Auto-distilled motion skill: product_card_swoop_focus.

A screenshot or card slips in from the right, fades cleanly, then gets a subtle focus pulse.

Category: composite. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'product_card_swoop_focus'
CATEGORY = 'composite'
DESCRIPTION = 'A screenshot or card slips in from the right, fades cleanly, then gets a subtle focus pulse.'

APPLICABILITY = {
    "roles": ['product_showcase', 'screenshot_callout', 'feature_spotlight', 'comparison_panel'],
    "anchor_names": ['product_shot', 'screenshot', 'device', 'mockup', 'ui_card'],
    "anchor_name_regex": '(?i)(product|screenshot|screen|device|mockup|ui|dashboard|app|card)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 180, 'min': 0, 'max': 900}, 'fly_ms': {'default': 680, 'min': 450, 'max': 900}, 'fade_ms': {'default': 420, 'min': 300, 'max': 700}, 'pulse_ms': {'default': 280, 'min': 220, 'max': 500}, 'pulse_pct': {'default': 103, 'min': 102, 'max': 106}}

TAGS = ['product', 'card', 'lateral', 'clean', 'showcase']
INTENSITY = 6
EMBEDDING_TEXT = (
    'A lateral showcase motion for product screenshots, UI cards, device mockups, and feature panels. The object flies in from the right with a clean fade, then receives a tiny focus pulse that mimics a camera settling on the subject. It is ideal for demo slides, app previews, side-by-side product comparisons, and SaaS interface reveals. The aesthetic is crisp, directional, and presentation-grade with medium intensity.'
)
CONTENT_MATCHERS = {'is_image_or_card': True, 'aspect_landscape': True, 'medium_large_shape': True, 'product_ui': True}
COMPLEMENTARY_WITH = ['image_ken_burns', 'background_parallax_glide']
CONFLICTS_WITH = ['slide_in_left', 'lateral_handoff_crossfade', 'panel_unveil_settle']


MOOD = ['editorial']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_fly_in, emit_pulse
    delay = int(p.get('delay_ms', 180))
    fly_ms = int(p.get('fly_ms', 680))
    fade_ms = int(p.get('fade_ms', 420))
    pulse_ms = int(p.get('pulse_ms', 280))
    pulse_pct = int(p.get('pulse_pct', 103))
    emit_fade_in(slide, target_shape, delay_ms=delay, duration_ms=fade_ms)
    emit_fly_in(slide, target_shape, direction='right', delay_ms=delay, duration_ms=fly_ms)
    emit_pulse(slide, target_shape, delay_ms=delay + fly_ms + 80, duration_ms=pulse_ms, scale_pct=pulse_pct, repeats=1)
