"""Auto-distilled motion skill: quote_lilt_reveal.

Poetic left-to-right quote reveal with a soft wipe and unhurried text cadence.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'quote_lilt_reveal'
CATEGORY = 'text'
DESCRIPTION = 'Poetic left-to-right quote reveal with a soft wipe and unhurried text cadence.'

APPLICABILITY = {
    "roles": ['quote', 'testimonial', 'pull_quote', 'cover'],
    "anchor_names": ['quote', 'testimonial', 'pull_quote', 'body'],
    "anchor_name_regex": '^(quote|testimonial|pull_quote|body)$',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 1500}, 'wipe_duration_ms': {'default': 640, 'min': 360, 'max': 960}, 'stagger_ms': {'default': 95, 'min': 40, 'max': 180}, 'per_duration_ms': {'default': 360, 'min': 220, 'max': 620}}

TAGS = ['quote', 'poetic', 'soft', 'literary', 'measured']
INTENSITY = 3
EMBEDDING_TEXT = (
    'This text skill is designed for pull quotes, testimonials, and reflective single-sentence statements. A soft left-to-right wipe establishes direction, then the text reveals in a slower, lyrical stagger that feels thoughtful and composed. The visual tone is gentle, human, and slightly cinematic without becoming dramatic. Use it for quotation marks, attributed statements, and slides where cadence matters as much as information.'
)
CONTENT_MATCHERS = {'has_quote_marks': True, 'is_quote': True, 'line_count_lte_4': True}
COMPLEMENTARY_WITH = ['focus_pull_dissolve', 'photo_wipe_drift']
CONFLICTS_WITH = ['quote_lens_arrive', 'cinematic_lateral_reveal']


MOOD = ['calm', 'editorial', 'playful', 'warm']
ARCHETYPE_FIT = ['narrative', 'research', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_fade_in, emit_text_stagger
    base_delay = int(p.get('delay_ms', 120))
    wipe_dur = int(p.get('wipe_duration_ms', 640))
    emit_wipe_in(slide, target_shape, direction='left', delay_ms=base_delay, duration_ms=wipe_dur)
    emit_fade_in(slide, target_shape, delay_ms=base_delay, duration_ms=max(260, wipe_dur - 180))
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + 120, stagger_ms=int(p.get('stagger_ms', 95)), per_duration_ms=int(p.get('per_duration_ms', 360)))
