"""Auto-distilled motion skill: quote_breath_arc.

Reflective quote reveal that fades in while drifting on a soft arc with slow text timing.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'quote_breath_arc'
CATEGORY = 'text'
DESCRIPTION = 'Reflective quote reveal that fades in while drifting on a soft arc with slow text timing.'

APPLICABILITY = {
    "roles": ['quote_slide', 'testimonial', 'case_study', 'section_divider'],
    "anchor_names": ['quote', 'pull_quote', 'testimonial', 'subhead'],
    "anchor_name_regex": '(?i)(quote|pull[_ ]?quote|testimonial)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 800}, 'fade_duration_ms': {'default': 620, 'min': 400, 'max': 1000}, 'float_duration_ms': {'default': 900, 'min': 600, 'max': 1200}, 'text_offset_ms': {'default': 120, 'min': 0, 'max': 260}, 'stagger_ms': {'default': 110, 'min': 60, 'max': 180}, 'per_duration_ms': {'default': 420, 'min': 240, 'max': 520}, 'dy_frac': {'default': -0.05, 'min': -0.12, 'max': 0.0}, 'bow_frac': {'default': 0.18, 'min': 0.08, 'max': 0.28}}

TAGS = ['quote', 'airy', 'reflective', 'editorial', 'slow']
INTENSITY = 3
EMBEDDING_TEXT = (
    'This is a soft, editorial text motion for pull quotes, testimonials, and thoughtful subheads. The whole text block fades in and glides on a shallow arc while the words or lines arrive with a measured, breathing cadence. It looks calm, intentional, and slightly cinematic without becoming flashy. Best for human voices, founder statements, and high-whitespace layouts.'
)
CONTENT_MATCHERS = {'quote_like': True, 'multi_line': True, 'is_headline': False}
COMPLEMENTARY_WITH = ['gentle_rise_fade', 'background_parallax_glide', 'glass_card_hover_loop']
CONFLICTS_WITH = ['headline_restrike_focus', 'dramatic_zoom', 'bounce_in']


MOOD = ['calm', 'editorial', 'cinematic', 'restrained']
ARCHETYPE_FIT = ['narrative', 'research', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_arc_path, emit_text_stagger
    base_delay = int(p.get('delay_ms', 120))
    fade_duration_ms = int(p.get('fade_duration_ms', 620))
    float_duration_ms = int(p.get('float_duration_ms', 900))
    text_offset_ms = int(p.get('text_offset_ms', 120))
    stagger_ms = int(p.get('stagger_ms', 110))
    per_duration_ms = int(p.get('per_duration_ms', 420))
    dy_frac = float(p.get('dy_frac', -0.05))
    bow_frac = float(p.get('bow_frac', 0.18))
    emit_fade_in(slide, target_shape, delay_ms=base_delay, duration_ms=fade_duration_ms)
    emit_arc_path(slide, target_shape, delay_ms=base_delay, duration_ms=float_duration_ms, dx_frac=0.0, dy_frac=dy_frac, bow_frac=bow_frac)
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + text_offset_ms, stagger_ms=stagger_ms, per_duration_ms=per_duration_ms)
