"""Auto-distilled motion skill: quote_arc_whisper.

A quote fades up on a shallow arc, then settles with a barely-there emphasis lift.

Category: composite. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'quote_arc_whisper'
CATEGORY = 'composite'
DESCRIPTION = 'A quote fades up on a shallow arc, then settles with a barely-there emphasis lift.'

APPLICABILITY = {
    "roles": ['quote', 'testimonial', 'pull_quote', 'section_divider'],
    "anchor_names": ['quote', 'pull_quote', 'testimonial', 'attribution'],
    "anchor_name_regex": '(quote|testimonial|pull[_ ]?quote|attribution)',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 160, 'min': 0, 'max': 1500}, 'fade_duration_ms': {'default': 480, 'min': 300, 'max': 800}, 'drift_duration_ms': {'default': 820, 'min': 500, 'max': 1200}, 'dx_frac': {'default': 0.0, 'min': -0.12, 'max': 0.12}, 'dy_frac': {'default': -0.06, 'min': -0.16, 'max': 0.0}, 'bow_frac': {'default': 0.08, 'min': -0.2, 'max': 0.25}, 'settle_duration_ms': {'default': 260, 'min': 200, 'max': 500}, 'settle_pct': {'default': 103, 'min': 101, 'max': 108}}

TAGS = ['elegant', 'editorial', 'soft', 'lyrical', 'premium']
INTENSITY = 4
EMBEDDING_TEXT = (
    'A soft editorial reveal for pull quotes, testimonials, and reflective statements. The shape fades in while drifting on a gentle arc, then resolves with a tiny settle emphasis that feels warm and intentional. It retrieves well for human-centered slides, customer praise, keynote interludes, and large quote compositions with attribution. Low-to-medium intensity, graceful motion, and a calm premium tone.'
)
CONTENT_MATCHERS = {'is_quote': True, 'multiword': True, 'line_count_le_5': True, 'has_attribution': True}
COMPLEMENTARY_WITH = ['subhead_glide_stagger', 'focus_pull_dissolve', 'image_ken_burns']
CONFLICTS_WITH = ['quote_lens_arrive', 'quote_lilt_reveal']


MOOD = ['editorial', 'calm', 'cinematic']
ARCHETYPE_FIT = ['narrative', 'research', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_arc_path, emit_grow_emphasis
    delay = int(p.get('delay_ms', 160))
    drift_dur = int(p.get('drift_duration_ms', 820))
    emit_fade_in(slide, target_shape, delay_ms=delay, duration_ms=int(p.get('fade_duration_ms', 480)))
    emit_arc_path(slide, target_shape, delay_ms=delay, duration_ms=drift_dur, dx_frac=float(p.get('dx_frac', 0.0)), dy_frac=float(p.get('dy_frac', -0.06)), bow_frac=float(p.get('bow_frac', 0.08)))
    emit_grow_emphasis(slide, target_shape, delay_ms=delay + drift_dur, duration_ms=int(p.get('settle_duration_ms', 260)), to_pct=int(p.get('settle_pct', 103)))
