"""Auto-distilled motion skill: quote_lens_arrive.

Gentle lens-like focus-in for quotes, testimonials, and key statements.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'quote_lens_arrive'
CATEGORY = 'entrance'
DESCRIPTION = 'Gentle lens-like focus-in for quotes, testimonials, and key statements.'

APPLICABILITY = {
    "roles": ['quote', 'testimonial', 'pull_quote', 'section_divider'],
    "anchor_names": ['quote', 'testimonial', 'pull_quote', 'statement'],
    "anchor_name_regex": '(?i)(quote|testimonial|pull.?quote|statement)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 100, 'min': 0, 'max': 900}, 'duration_ms': {'default': 760, 'min': 500, 'max': 1000}, 'from_pct': {'default': 93, 'min': 85, 'max': 98}}

TAGS = ['warm', 'refined', 'focus', 'text', 'storytelling']
INTENSITY = 4
EMBEDDING_TEXT = (
    'A quote or testimonial eases forward as if a camera lens is settling into focus. The scale change is intentionally small, which keeps longer text readable and emotionally calm while still giving it presence. Use it for pull quotes, founder statements, customer testimonials, and other narrative text blocks that need a polished entrance. Strong retrieval phrases include quote zoom-in, testimonial focus reveal, warm text entrance, and subtle lens effect.'
)
CONTENT_MATCHERS = {'is_quote': True, 'medium_text': True, 'digits': False}
COMPLEMENTARY_WITH = ['headline_word_cascade', 'breathing_halo']
CONFLICTS_WITH = ['zoom_from_center', 'dramatic_zoom']


MOOD = ['editorial', 'warm', 'restrained', 'cinematic']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_zoom_in, emit_fade_in
    d = int(p.get('delay_ms', 100))
    dur = int(p.get('duration_ms', 760))
    fp = int(p.get('from_pct', 93))
    emit_zoom_in(slide, target_shape, delay_ms=d, duration_ms=dur, from_pct=fp)
    emit_fade_in(slide, target_shape, delay_ms=d, duration_ms=max(340, int(dur * 0.8)))
