"""Auto-distilled motion skill: quote_lantern_reveal.

Quote text fades and staggers in while drifting on a soft upward editorial arc.

Category: composite. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'quote_lantern_reveal'
CATEGORY = 'composite'
DESCRIPTION = 'Quote text fades and staggers in while drifting on a soft upward editorial arc.'

APPLICABILITY = {
    "roles": ['quote_callout', 'testimonial', 'cover', 'pull_quote'],
    "anchor_names": ['quote', 'testimonial', 'pull_quote', 'customer_quote'],
    "anchor_name_regex": '(?i)(quote|testimonial|pull[_ ]?quote|customer[_ ]?quote|endorsement)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 140, 'min': 0, 'max': 800}, 'fade_ms': {'default': 420, 'min': 300, 'max': 700}, 'stagger_ms': {'default': 80, 'min': 40, 'max': 160}, 'per_line_ms': {'default': 320, 'min': 220, 'max': 520}, 'drift_ms': {'default': 760, 'min': 500, 'max': 1000}, 'dx_frac': {'default': 0.012, 'min': -0.04, 'max': 0.04}, 'dy_frac': {'default': -0.025, 'min': -0.06, 'max': 0.02}, 'bow_frac': {'default': 0.16, 'min': 0.08, 'max': 0.28}}

TAGS = ['editorial', 'quote', 'poised', 'cinematic', 'text']
INTENSITY = 4
EMBEDDING_TEXT = (
    'An editorial composite for quotes, testimonials, and pull-quote moments. The text fades up, reveals in staggered fragments, and glides on a very light arc so it feels lifted into view rather than merely animated. This works especially well for multi-line statements, customer praise, keynote pull quotes, and brand manifesto slides. The effect is tasteful, airy, and emotionally warm with low-to-medium intensity.'
)
CONTENT_MATCHERS = {'is_quote': True, 'multi_line': True, 'has_punctuation': True, 'is_text_box': True}
COMPLEMENTARY_WITH = ['cinematic_veil_reveal', 'background_parallax_glide']
CONFLICTS_WITH = ['headline_word_cascade', 'bullet_stagger_reveal', 'headline_prism_stagger']


MOOD = ['editorial', 'calm', 'cinematic']
ARCHETYPE_FIT = ['narrative', 'research', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_text_stagger, emit_arc_path
    delay = int(p.get('delay_ms', 140))
    fade_ms = int(p.get('fade_ms', 420))
    stagger_ms = int(p.get('stagger_ms', 80))
    per_line_ms = int(p.get('per_line_ms', 320))
    drift_ms = int(p.get('drift_ms', 760))
    dx_frac = float(p.get('dx_frac', 0.012))
    dy_frac = float(p.get('dy_frac', -0.025))
    bow_frac = float(p.get('bow_frac', 0.16))
    emit_fade_in(slide, target_shape, delay_ms=delay, duration_ms=fade_ms)
    emit_text_stagger(slide, target_shape, delay_ms=delay + 40, stagger_ms=stagger_ms, per_duration_ms=per_line_ms)
    emit_arc_path(slide, target_shape, delay_ms=delay, duration_ms=drift_ms, dx_frac=dx_frac, dy_frac=dy_frac, bow_frac=bow_frac)
