"""Auto-distilled motion skill: runway_push_transition.

An assertive camera-push reveal with side wipe, ideal for screenshots and hero media.

Category: transition. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'runway_push_transition'
CATEGORY = 'transition'
DESCRIPTION = 'An assertive camera-push reveal with side wipe, ideal for screenshots and hero media.'

APPLICABILITY = {
    "roles": ['hero_media', 'product_showcase', 'dashboard', 'full_bleed_image', 'cover'],
    "anchor_names": ['hero_image', 'screenshot', 'dashboard', 'device_frame', 'chart'],
    "anchor_name_regex": '^(hero_image|screenshot|dashboard|device_frame|chart)$',
    "max_per_slide": 1,
}

PARAMETERS = {'delay_ms': {'default': 100, 'min': 0, 'max': 450}, 'zoom_duration_ms': {'default': 1300, 'min': 800, 'max': 1800}, 'wipe_duration_ms': {'default': 900, 'min': 600, 'max': 1400}, 'fade_duration_ms': {'default': 520, 'min': 350, 'max': 800}, 'from_pct': {'default': 92, 'min': 84, 'max': 98}}

TAGS = ['push', 'camera', 'hero', 'media', 'assertive']
INTENSITY = 7
EMBEDDING_TEXT = (
    'This transition reads like a camera push through into the next scene. A screenshot, dashboard, or hero image zooms in from slightly smaller scale while a directional wipe clarifies the handoff and a short fade removes any harsh edge. It is strongest on product UI, full-bleed media, and showcase visuals that should feel immersive and intentional. The intensity is higher than a soft dissolve, but still polished and presentation-grade.'
)
CONTENT_MATCHERS = {'is_screenshot': True, 'has_image': True, 'wide_shape': True, 'is_hero': True}
COMPLEMENTARY_WITH = ['count_up_metric', 'chart_bar_grow', 'image_ken_burns']
CONFLICTS_WITH = ['dramatic_zoom', 'hero_lens_focus', 'zoom_from_center']


MOOD = ['bold', 'cinematic', 'punchy']
ARCHETYPE_FIT = ['brand', 'product', 'narrative']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_wipe_in, emit_zoom_in
    _delay = int(p.get('delay_ms', 100))
    _zoom_ms = int(p.get('zoom_duration_ms', 1300))
    _wipe_ms = int(p.get('wipe_duration_ms', 900))
    _fade_ms = int(p.get('fade_duration_ms', 520))
    _from_pct = int(p.get('from_pct', 92))
    emit_fade_in(slide, target_shape, delay_ms=_delay, duration_ms=_fade_ms)
    emit_wipe_in(slide, target_shape, direction='right', delay_ms=_delay, duration_ms=_wipe_ms)
    emit_zoom_in(slide, target_shape, delay_ms=_delay, duration_ms=_zoom_ms, from_pct=_from_pct)
