"""Auto-distilled motion skill: seal_twirl_land.

Compact rotational pop-in for logos, seals, icons, and badge accents.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'seal_twirl_land'
CATEGORY = 'entrance'
DESCRIPTION = 'Compact rotational pop-in for logos, seals, icons, and badge accents.'

APPLICABILITY = {
    "roles": ['badge', 'logo', 'icon_callout', 'cta_chip'],
    "anchor_names": ['logo', 'badge', 'seal', 'icon', 'cta'],
    "anchor_name_regex": '(?i)(logo|badge|seal|icon|cta|chip|sticker)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 1000}, 'duration_ms': {'default': 640, 'min': 450, 'max': 900}, 'from_deg': {'default': -18, 'min': -60, 'max': 60}, 'from_pct': {'default': 76, 'min': 60, 'max': 95}}

TAGS = ['playful', 'confident', 'brand', 'accent', 'compact']
INTENSITY = 6
EMBEDDING_TEXT = (
    'This is a tidy brand-accent entrance: a small twist plus a scale-up that lands with confidence. It suits logos, seals, feature badges, sticker-like callouts, and compact icon moments that should feel lively without becoming cartoonish. Compared with larger spins, the angle is modest and the footprint stays contained. Good retrieval phrases are logo twirl, badge pop-in, brand accent entrance, and compact rotational reveal.'
)
CONTENT_MATCHERS = {'is_logo': True, 'is_badge_like': True, 'short_text': True}
COMPLEMENTARY_WITH = ['pulse_emphasis', 'orbital_accent']
CONFLICTS_WITH = ['badge_pinwheel_pop', 'badge_swing_in', 'rotate_in']


MOOD = ['playful', 'punchy', 'editorial']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_rotate_in, emit_grow_from_small
    d = int(p.get('delay_ms', 120))
    dur = int(p.get('duration_ms', 640))
    deg = int(p.get('from_deg', -18))
    fp = int(p.get('from_pct', 76))
    emit_rotate_in(slide, target_shape, delay_ms=d, duration_ms=dur, from_deg=deg)
    emit_grow_from_small(slide, target_shape, delay_ms=d, duration_ms=max(360, int(dur * 0.9)), from_pct=fp)
