"""Auto-distilled motion skill: seal_slow_spin.

Ultra-slow continuous spin for circular seals, logos, and medallion marks.

Category: ambient. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'seal_slow_spin'
CATEGORY = 'ambient'
DESCRIPTION = 'Ultra-slow continuous spin for circular seals, logos, and medallion marks.'

APPLICABILITY = {
    "roles": ['cover', 'logo_lockup', 'badge', 'closing'],
    "anchor_names": ['logo', 'seal', 'badge', 'medallion'],
    "anchor_name_regex": '.*(logo|seal|badge|medallion).*',
    "max_per_slide": 1,
}

PARAMETERS = {'duration_ms': {'default': 8000, 'min': 5000, 'max': 10000}}

TAGS = ['polished', 'ceremonial', 'brand', 'minimal', 'steady']
INTENSITY = 2
EMBEDDING_TEXT = (
    'A very slow continuous rotation gives circular logos, certification seals, and stamp-like marks a refined sense of presence. The aesthetic is polished and ceremonial rather than playful, making it appropriate for brand pages, covers, and closing slides. Because the spin is so slow, it reads as premium motion texture instead of a literal spinner. It shines on round geometry, emblems, and simple iconography with strong silhouette recognition.'
)
CONTENT_MATCHERS = {'is_logo': True, 'is_badge': True, 'is_circular': True}
COMPLEMENTARY_WITH = ['rotate_in', 'badge_swing_in']
CONFLICTS_WITH = ['counter_rotate_cog', 'seal_tilt_reaffirm']


MOOD = ['calm', 'restrained']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _shell_helpers import add_infinite_rotation
    add_infinite_rotation(
        slide,
        target_shape,
        duration_ms=int(p.get('duration_ms', 8000)),
        direction='clockwise',
    )
