"""Auto-distilled motion skill: seal_tilt_reaffirm.

Badges, chips, and logos reassert themselves with a tiny stamped tilt and tighten.

Category: emphasis. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'seal_tilt_reaffirm'
CATEGORY = 'emphasis'
DESCRIPTION = 'Badges, chips, and logos reassert themselves with a tiny stamped tilt and tighten.'

APPLICABILITY = {
    "roles": ['badge', 'logo_lockup', 'chip', 'pill', 'award', 'certification'],
    "anchor_names": ['badge', 'logo', 'chip', 'pill', 'seal', 'tag'],
    "anchor_name_regex": '(badge|logo|chip|pill|seal|tag)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 100, 'min': 0, 'max': 1000}, 'duration_ms': {'default': 440, 'min': 320, 'max': 760}, 'from_deg': {'default': 5, 'min': 2, 'max': 10}, 'from_pct': {'default': 97, 'min': 92, 'max': 99}}

TAGS = ['stamp', 'brand', 'badge', 'assertive', 'polished']
INTENSITY = 6
EMBEDDING_TEXT = (
    'This emphasis feels like a quick reaffirmation stamp for logos, badges, seals, and compact branded chips. A tiny rotational entry combines with a near-full-size tighten so the object appears to re-seat itself with confidence. It works well for trust marks, awards, partner logos, and feature tags that need a moment of importance. The mood is assertive and tactile, but still clean enough for premium corporate decks.'
)
CONTENT_MATCHERS = {'has_icon': True, 'is_logo': True, 'short_text': True, 'digits': False, 'is_headline': False}
COMPLEMENTARY_WITH = ['editorial_wipe_rise', 'orbital_accent']
CONFLICTS_WITH = ['badge_swing_in', 'rotate_in']


MOOD = ['playful', 'editorial', 'punchy']
ARCHETYPE_FIT = ['product', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_rotate_in, emit_grow_from_small
    base_delay = int(p.get('delay_ms', 100))
    base_dur = int(p.get('duration_ms', 440))
    from_deg = int(p.get('from_deg', 5))
    from_pct = int(p.get('from_pct', 97))
    emit_rotate_in(slide, target_shape, delay_ms=base_delay, duration_ms=max(260, base_dur - 120), from_deg=from_deg)
    emit_grow_from_small(slide, target_shape, delay_ms=base_delay + 40, duration_ms=max(260, base_dur - 40), from_pct=from_pct)
