"""Auto-distilled motion skill: signal_beacon_idle.

Soft pulse with tiny drift for pins, badges, status chips, and compact CTA accents.

Category: ambient. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'signal_beacon_idle'
CATEGORY = 'ambient'
DESCRIPTION = 'Soft pulse with tiny drift for pins, badges, status chips, and compact CTA accents.'

APPLICABILITY = {
    "roles": ['badge', 'map_pin', 'status_callout', 'cta_chip', 'feature_icon'],
    "anchor_names": ['badge', 'icon', 'pin', 'cta', 'status'],
    "anchor_name_regex": '(badge|icon|pin|cta|status|chip)',
    "max_per_slide": 3,
}

PARAMETERS = {'pulse_duration_ms': {'default': 3200, 'min': 2200, 'max': 5200}, 'scale_pct': {'default': 105, 'min': 102, 'max': 110}, 'drift_duration_ms': {'default': 4600, 'min': 2800, 'max': 7000}, 'dx_in': {'default': 0.04, 'min': -0.12, 'max': 0.12}, 'dy_in': {'default': -0.05, 'min': -0.12, 'max': 0.12}}

TAGS = ['subtle', 'lively', 'beacon', 'ui', 'accent']
INTENSITY = 4
EMBEDDING_TEXT = (
    'This ambient loop makes a small target feel like a live signal instead of a static object. The visual language is a restrained beacon: a gentle size pulse paired with a tiny hover drift, ideal for map pins, CTA badges, status chips, and compact feature icons. It reads as active, clickable, and current without becoming flashy. Use it when you want subtle energy on small accents rather than large hero visuals.'
)
CONTENT_MATCHERS = {'is_icon': True, 'is_badge': True, 'is_small_shape': True, 'is_cta': True, 'is_metric': False}
COMPLEMENTARY_WITH = ['badge_swing_in', 'panel_unveil_settle', 'slide_in_left']
CONFLICTS_WITH = ['breathing_halo', 'hero_metric_heartbeat_loop', 'floating_card_drift']


MOOD = ['technical', 'calm', 'editorial']
ARCHETYPE_FIT = ['data', 'product']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _shell_helpers import add_pulse_loop, add_drift_motion
    add_pulse_loop(
        slide,
        target_shape,
        duration_ms=int(p.get('pulse_duration_ms', 3200)),
        scale_pct=int(p.get('scale_pct', 105)),
    )
    add_drift_motion(
        slide,
        target_shape,
        dx_in=float(p.get('dx_in', 0.04)),
        dy_in=float(p.get('dy_in', -0.05)),
        duration_ms=int(p.get('drift_duration_ms', 4600)),
        pingpong=True,
    )
