"""Auto-distilled motion skill: soft_arc_settle.

Fade in along a shallow arc for polished editorial headlines, quotes, and feature cards.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'soft_arc_settle'
CATEGORY = 'entrance'
DESCRIPTION = 'Fade in along a shallow arc for polished editorial headlines, quotes, and feature cards.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'quote', 'hero_statement', 'feature_card'],
    "anchor_names": ['headline', 'quote', 'eyebrow', 'title', 'card_title'],
    "anchor_name_regex": '(headline|title|quote|eyebrow|card_title)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 600}, 'fade_duration_ms': {'default': 420, 'min': 250, 'max': 700}, 'move_duration_ms': {'default': 760, 'min': 400, 'max': 1100}, 'dx_frac': {'default': 0.0, 'min': -0.15, 'max': 0.15}, 'dy_frac': {'default': -0.08, 'min': -0.2, 'max': 0.0}, 'bow_frac': {'default': 0.18, 'min': 0.05, 'max': 0.35}}

TAGS = ['editorial', 'graceful', 'premium', 'subtle', 'curved']
INTENSITY = 3
EMBEDDING_TEXT = (
    'This entrance feels like the object glides into place on a shallow magazine-style arc, then settles with composure. It suits headlines, pull quotes, and refined feature cards where the tone should feel premium, calm, and intentional rather than flashy. The motion is subtle, slightly curved, and especially effective on modern cover slides or section breaks with generous whitespace.'
)
CONTENT_MATCHERS = {'is_headline': True, 'short_text': True, 'digits': False, 'large_visual': False}
COMPLEMENTARY_WITH = ['image_ken_burns', 'bullet_stagger_reveal']
CONFLICTS_WITH = ['dramatic_zoom', 'headline_word_cascade']


MOOD = ['editorial', 'calm', 'cinematic', 'restrained']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_arc_path
    emit_fade_in(slide, target_shape,
                 delay_ms=int(p.get('delay_ms', 120)),
                 duration_ms=int(p.get('fade_duration_ms', 420)))
    emit_arc_path(slide, target_shape,
                  delay_ms=int(p.get('delay_ms', 120)),
                  duration_ms=int(p.get('move_duration_ms', 760)),
                  dx_frac=float(p.get('dx_frac', 0.0)),
                  dy_frac=float(p.get('dy_frac', -0.08)),
                  bow_frac=float(p.get('bow_frac', 0.18)))
