"""Auto-distilled motion skill: stat_scan_reveal.

Bottom-up scan reveal with a crisp finishing pulse for metrics and prices.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'stat_scan_reveal'
CATEGORY = 'entrance'
DESCRIPTION = 'Bottom-up scan reveal with a crisp finishing pulse for metrics and prices.'

APPLICABILITY = {
    "roles": ['hero_giant_metric', 'kpi', 'pricing', 'score', 'timeline_metric'],
    "anchor_names": ['metric', 'stat', 'kpi', 'number', 'price', 'percent'],
    "anchor_name_regex": '(?i)(metric|stat|kpi|number|value|price|percent|score|total)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 1200}, 'wipe_duration_ms': {'default': 520, 'min': 400, 'max': 800}, 'pulse_duration_ms': {'default': 360, 'min': 300, 'max': 700}, 'scale_pct': {'default': 107, 'min': 103, 'max': 112}}

TAGS = ['crisp', 'data', 'confident', 'numeric', 'sharp']
INTENSITY = 6
EMBEDDING_TEXT = (
    'This metric entrance reads like a quick scan line rising through the number, followed by a controlled pop of emphasis. It is designed for bold KPIs, pricing figures, percentages, scores, and short numerical callouts that benefit from precision and punch. The result is sharper and more data-oriented than a generic zoom or bounce. Retrieval cues include KPI reveal, percentage scan-in, pricing stat entrance, and numeric pulse finish.'
)
CONTENT_MATCHERS = {'digits': True, 'contains_percent': True, 'short_text': True}
COMPLEMENTARY_WITH = ['count_up_metric', 'chart_bar_grow']
CONFLICTS_WITH = ['metric_snap_focus', 'grow_reveal']


MOOD = ['technical', 'boardroom', 'editorial']
ARCHETYPE_FIT = ['data', 'boardroom']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_pulse
    d = int(p.get('delay_ms', 120))
    wd = int(p.get('wipe_duration_ms', 520))
    pd = int(p.get('pulse_duration_ms', 360))
    sp = int(p.get('scale_pct', 107))
    emit_wipe_in(slide, target_shape, direction='bottom', delay_ms=d, duration_ms=wd)
    emit_pulse(slide, target_shape, delay_ms=d + wd - 40, duration_ms=pd, scale_pct=sp, repeats=1)
