"""Auto-distilled motion skill: subhead_glide_stagger.

Bottom-up subhead reveal that guides reading with gentle motion and quick sequencing.

Category: text. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'subhead_glide_stagger'
CATEGORY = 'text'
DESCRIPTION = 'Bottom-up subhead reveal that guides reading with gentle motion and quick sequencing.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'content_intro', 'two_column'],
    "anchor_names": ['subhead', 'dek', 'intro', 'eyebrow'],
    "anchor_name_regex": '^(subhead|dek|intro|eyebrow)$',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 80, 'min': 0, 'max': 1400}, 'fly_duration_ms': {'default': 520, 'min': 320, 'max': 820}, 'stagger_ms': {'default': 70, 'min': 25, 'max': 140}, 'per_duration_ms': {'default': 320, 'min': 180, 'max': 560}}

TAGS = ['subhead', 'guided', 'clean', 'reading-order', 'modern']
INTENSITY = 4
EMBEDDING_TEXT = (
    'This motion gives a subhead or deck a clear upward glide, then hands off to a tidy text stagger that improves scanability. It feels modern and presentational, like a keynote subtitle arriving just after the main headline. The style suits explanatory lines, deck copy, and short supporting text under a hero statement. Use it when you want readable motion with a little more energy than a plain fade.'
)
CONTENT_MATCHERS = {'is_subhead': True, 'multiword': True, 'line_count_lte_3': True}
COMPLEMENTARY_WITH = ['headline_letterpress_stagger', 'cinematic_lateral_reveal']
CONFLICTS_WITH = ['subhead_stagger_fade', 'editorial_wipe_rise']


MOOD = ['editorial']
ARCHETYPE_FIT = ['narrative', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fly_in, emit_fade_in, emit_text_stagger
    base_delay = int(p.get('delay_ms', 80))
    fly_dur = int(p.get('fly_duration_ms', 520))
    emit_fly_in(slide, target_shape, direction='bottom', delay_ms=base_delay, duration_ms=fly_dur)
    emit_fade_in(slide, target_shape, delay_ms=base_delay, duration_ms=max(220, fly_dur - 120))
    emit_text_stagger(slide, target_shape, delay_ms=base_delay + 100, stagger_ms=int(p.get('stagger_ms', 70)), per_duration_ms=int(p.get('per_duration_ms', 320)))
