"""Auto-distilled motion skill: subhead_mask_stagger.

A subhead wipes on like a mask reveal, then its text staggers through for crisp editorial rhythm.

Category: composite. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'subhead_mask_stagger'
CATEGORY = 'composite'
DESCRIPTION = 'A subhead wipes on like a mask reveal, then its text staggers through for crisp editorial rhythm.'

APPLICABILITY = {
    "roles": ['cover', 'section_header', 'agenda', 'two_column_text', 'caption_block'],
    "anchor_names": ['subhead', 'dek', 'caption', 'label', 'body'],
    "anchor_name_regex": '(subhead|dek|caption|label|subtitle)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 180, 'min': 0, 'max': 1200}, 'wipe_duration_ms': {'default': 650, 'min': 450, 'max': 1100}, 'stagger_offset_ms': {'default': 80, 'min': 0, 'max': 240}, 'stagger_ms': {'default': 55, 'min': 25, 'max': 140}, 'per_duration_ms': {'default': 340, 'min': 220, 'max': 600}, 'settle_duration_ms': {'default': 220, 'min': 160, 'max': 400}, 'settle_pct': {'default': 102, 'min': 101, 'max': 106}}

TAGS = ['editorial', 'text', 'structured', 'sharp', 'refined']
INTENSITY = 5
EMBEDDING_TEXT = (
    'A crisp text treatment for subheads, dek lines, captions, and compact supporting copy. The block first appears through a mask-like wipe, then the text itself staggers through for layered editorial rhythm before a tiny settle locks it in place. It retrieves well for magazine-style covers, section headers, product descriptors, and short explanatory text that should feel designed rather than merely faded in. Medium intensity with typography-first motion and strong readability.'
)
CONTENT_MATCHERS = {'is_text': True, 'multiword': True, 'line_count_le_3': True, 'is_subhead': True}
COMPLEMENTARY_WITH = ['focus_pull_dissolve', 'image_ken_burns', 'headline_letterpress_stagger']
CONFLICTS_WITH = ['subhead_stagger_fade', 'headline_word_cascade', 'editorial_wipe_rise']


MOOD = ['editorial', 'calm', 'restrained']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_wipe_in, emit_text_stagger, emit_grow_emphasis
    delay = int(p.get('delay_ms', 180))
    wipe_dur = int(p.get('wipe_duration_ms', 650))
    emit_wipe_in(slide, target_shape, direction='left', delay_ms=delay, duration_ms=wipe_dur)
    emit_text_stagger(slide, target_shape, delay_ms=delay + int(p.get('stagger_offset_ms', 80)), stagger_ms=int(p.get('stagger_ms', 55)), per_duration_ms=int(p.get('per_duration_ms', 340)))
    emit_grow_emphasis(slide, target_shape, delay_ms=delay + wipe_dur, duration_ms=int(p.get('settle_duration_ms', 220)), to_pct=int(p.get('settle_pct', 102)))
