"""Auto-distilled motion skill: subhead_stagger_fade.

Soft staggered text reveal for subheads, quotes, and lead-in copy.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'subhead_stagger_fade'
CATEGORY = 'entrance'
DESCRIPTION = 'Soft staggered text reveal for subheads, quotes, and lead-in copy.'

APPLICABILITY = {
    "roles": ['cover', 'section_divider', 'quote', 'body_lead'],
    "anchor_names": ['subhead', 'subtitle', 'quote', 'body', 'caption'],
    "anchor_name_regex": '(?i)(subhead|subtitle|quote|caption|body)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 120, 'min': 0, 'max': 1200}, 'fade_ms': {'default': 240, 'min': 160, 'max': 420}, 'stagger_ms': {'default': 70, 'min': 30, 'max': 140}, 'per_duration_ms': {'default': 520, 'min': 320, 'max': 700}}

TAGS = ['text', 'subtle', 'copy', 'stagger', 'editorial']
INTENSITY = 3
EMBEDDING_TEXT = (
    'This reveals text in a gentle stagger while the whole text box fades up, producing a calm, composed reading experience. It suits subheads, quotes, captions, and lead paragraphs that need refinement rather than spectacle. Compared with more dramatic headline cascades, this version is softer, more legible, and better for multi-line copy. Use it when rhythm and readability matter more than showmanship.'
)
CONTENT_MATCHERS = {'is_headline': False, 'multi_line_text': True, 'short_text': False, 'digits': False, 'has_image': False}
COMPLEMENTARY_WITH = ['headline_arc_settle', 'photo_wipe_drift']
CONFLICTS_WITH = ['headline_word_cascade', 'bullet_stagger_reveal']


MOOD = ['editorial', 'calm', 'restrained']
ARCHETYPE_FIT = ['narrative', 'brand', 'research']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_fade_in, emit_text_stagger
    base = int(p.get('delay_ms', 120))
    emit_fade_in(slide, target_shape, delay_ms=base, duration_ms=int(p.get('fade_ms', 240)))
    emit_text_stagger(slide, target_shape, delay_ms=base, stagger_ms=int(p.get('stagger_ms', 70)), per_duration_ms=int(p.get('per_duration_ms', 520)))
