"""Auto-distilled motion skill: tilt_drop_land.

A top-down drop with slight rotation for badges, logos, stickers, and callout chips.

Category: entrance. Generated by scripts/distill_motion_skills.py.
"""
from __future__ import annotations

NAME = 'tilt_drop_land'
CATEGORY = 'entrance'
DESCRIPTION = 'A top-down drop with slight rotation for badges, logos, stickers, and callout chips.'

APPLICABILITY = {
    "roles": ['badge', 'logo', 'callout', 'annotation', 'label_chip'],
    "anchor_names": ['badge', 'logo', 'callout', 'sticker', 'label'],
    "anchor_name_regex": '(badge|logo|callout|sticker|label)',
    "max_per_slide": 2,
}

PARAMETERS = {'delay_ms': {'default': 0, 'min': 0, 'max': 300}, 'duration_ms': {'default': 640, 'min': 450, 'max': 900}, 'from_deg': {'default': -10, 'min': -25, 'max': 25}}

TAGS = ['playful', 'badge', 'kinetic', 'angular', 'attention']
INTENSITY = 7
EMBEDDING_TEXT = (
    'This motion feels like a tag or sticker dropping into frame and catching itself with a slight tilt. It is best for compact objects such as badges, logos, annotations, and promotional chips that should feel lively and tactile. The look is energetic and visible, but still cleaner and more controlled than a full swing or cartoon bounce.'
)
CONTENT_MATCHERS = {'is_badge': True, 'small_object': True, 'is_headline': False, 'digits': False}
COMPLEMENTARY_WITH = ['orbital_accent', 'counter_rotate_cog']
CONFLICTS_WITH = ['badge_swing_in', 'rotate_in']


MOOD = ['playful', 'punchy', 'bold']
ARCHETYPE_FIT = ['product', 'brand']

def apply(slide, target_shape, params=None):
    p = dict(params or {})
    from _motion_helpers import emit_rotate_in, emit_fly_in
    emit_rotate_in(slide, target_shape,
                   delay_ms=int(p.get('delay_ms', 0)),
                   duration_ms=int(p.get('duration_ms', 640)),
                   from_deg=int(p.get('from_deg', -10)))
    emit_fly_in(slide, target_shape,
                direction='top',
                delay_ms=int(p.get('delay_ms', 0)),
                duration_ms=int(p.get('duration_ms', 640)))
