def create_component(
    output_dir: str,
    title_text: str = "Scroll-Driven CSS",
    body_text: str = "Scroll down to see native viewport animations.",
    color_scheme: str = "dark",
    accent_color: str = "#00e5ff",
    width_px: int = 1200,
    height_px: int = 800,
    **kwargs,
) -> dict:
    """
    Create a web component reproducing Scroll-Driven Viewport Animations and CSS Keyframes.
    Writes index.html, style.css, and script.js to output_dir.
    """
    import os

    os.makedirs(output_dir, exist_ok=True)

    # Derive theme colors
    if color_scheme == "dark":
        bg_color = "#121418"
        text_color = "#f3f4f6"
    else:
        bg_color = "#f9fafb"
        text_color = "#111827"

    # === CSS ===
    css = f"""/* Native CSS Scroll Animations & Transitions */
*, *::before, *::after {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

:root {{
    --bg: {bg_color};
    --text: {text_color};
    --accent: {accent_color};
}}

body {{
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    background: var(--bg);
    color: var(--text);
    min-height: 100vh;
    overflow-x: hidden;
}}

.hero {{
    height: 60vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    gap: 2rem;
}}

.title-group h1 {{
    font-size: 3.5rem;
    font-weight: 800;
    letter-spacing: -0.05em;
    margin-bottom: 0.5rem;
}}

.title-group p {{
    font-size: 1.25rem;
    opacity: 0.8;
}}

/* 1. Continuous Loading/Spinner Animation */
@keyframes spin3d {{
    0%   {{ transform: rotateX(0deg) rotateY(0deg) rotateZ(0deg); }}
    33%  {{ transform: rotateX(180deg) rotateY(0deg) rotateZ(0deg); }}
    67%  {{ transform: rotateX(180deg) rotateY(180deg) rotateZ(0deg); }}
    100% {{ transform: rotateX(180deg) rotateY(180deg) rotateZ(180deg); }}
}}

.spinner {{
    width: 60px;
    height: 60px;
    border: 6px solid var(--accent);
    border-radius: 8px;
    box-shadow: 0 0 15px var(--accent), inset 0 0 15px var(--accent);
    /* Shorthand animation properties as taught in tutorial */
    animation: spin3d 2s ease-in-out infinite both;
}}

/* Grid Layout */
.grid-container {{
    max-width: {width_px}px;
    margin: 0 auto;
    padding: 4rem 2rem;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
    grid-auto-rows: 150px;
    gap: 20px;
    grid-auto-flow: dense;
}}

/* Masonry variance classes */
.span-col {{ grid-column: span 2; }}
.span-row {{ grid-row: span 2; }}

/* 2. Scroll Animation Setup */
@keyframes scrollReveal {{
    from {{
        opacity: 0;
        transform: scale(0.5) translateY(50px);
    }}
    to {{
        opacity: 1;
        transform: scale(1) translateY(0);
    }}
}}

.card-wrapper {{
    /* Outer wrapper handles the scroll entry animation */
    will-change: transform, opacity;
}}

/* Apply Native Viewport Timeline IF supported */
@supports (animation-timeline: view()) {{
    .card-wrapper {{
        animation: scrollReveal linear both;
        animation-timeline: view();
        /* Start when entering, finish when 40% into view */
        animation-range: entry 0% cover 40%;
    }}
}}

/* Fallback for browsers without animation-timeline (Safari, Firefox) */
@supports not (animation-timeline: view()) {{
    .card-wrapper {{
        opacity: 0;
        transform: scale(0.5) translateY(50px);
        transition: opacity 0.8s cubic-bezier(0.2, 0.8, 0.2, 1), transform 0.8s cubic-bezier(0.2, 0.8, 0.2, 1);
    }}
    .card-wrapper.in-view {{
        opacity: 1;
        transform: scale(1) translateY(0);
    }}
}}

/* 3. Transition Hover Setup */
.card {{
    width: 100%;
    height: 100%;
    border-radius: 6px;
    background-color: var(--card-bg);
    /* Inner element handles the hover transition to avoid conflicts with scroll transform */
    transition: transform 0.3s ease-out, box-shadow 0.3s ease-out;
}}

.card:hover {{
    transform: scale(1.05) rotate(2deg);
    box-shadow: 0 15px 30px rgba(0, 0, 0, 0.4);
    z-index: 10;
    position: relative;
}}
"""

    # === HTML ===
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title_text}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header class="hero">
        <div class="spinner"></div>
        <div class="title-group">
            <h1>{title_text}</h1>
            <p>{body_text}</p>
        </div>
    </header>
    
    <main class="grid-container" id="grid">
        <!-- Grid items generated by JS -->
    </main>

    <script src="script.js"></script>
</body>
</html>"""

    # === JavaScript ===
    js = f"""document.addEventListener('DOMContentLoaded', () => {{
    const grid = document.getElementById('grid');
    
    // Retro-modern palette inspired by the tutorial's scrolling grid
    const palette = ["#d9382e", "#f3e5d0", "#148e91", "#645c71", "#eeb15b", "#2c3e50", "#e74c3c", "#f1c40f"];
    const spans = ['', '', '', 'span-col', 'span-col', 'span-row'];

    // Dynamically generate blocks to create a scrollable masonry layout
    for (let i = 0; i < 40; i++) {{
        const wrapper = document.createElement('div');
        wrapper.className = 'card-wrapper';
        
        // Randomly assign column/row spanning for masonry effect
        const spanClass = spans[Math.floor(Math.random() * spans.length)];
        if (spanClass) wrapper.classList.add(spanClass);

        const card = document.createElement('div');
        card.className = 'card';
        
        // Randomize background color
        const color = palette[Math.floor(Math.random() * palette.length)];
        card.style.setProperty('--card-bg', color);

        wrapper.appendChild(card);
        grid.appendChild(wrapper);
    }}

    // Fallback logic for browsers that don't support CSS view() timelines (e.g., Safari)
    if (!CSS.supports('animation-timeline: view()')) {{
        console.log("animation-timeline not supported, using IntersectionObserver fallback.");
        const observer = new IntersectionObserver((entries) => {{
            entries.forEach(entry => {{
                if (entry.isIntersecting) {{
                    entry.target.classList.add('in-view');
                    observer.unobserve(entry.target); // Only animate once
                }}
            }});
        }}, {{ threshold: 0.15, rootMargin: "0px 0px -50px 0px" }});

        document.querySelectorAll('.card-wrapper').forEach(el => observer.observe(el));
    }}
}});
"""

    # === Write files ===
    files = []
    for fname, content in [("index.html", html), ("style.css", css), ("script.js", js)]:
        path = os.path.join(output_dir, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        files.append(path)

    return {
        "html": html,
        "css": css,
        "js": js,
        "files": files,
    }
