def create_pattern(
    project_name: str = "MyProject",
    **kwargs
) -> str:
    """
    Creates two track templates demonstrating how to capture/record MIDI 
    generated by VST plugins (arpeggiators, chord generators) in REAPER.
    """
    import reaper_python as RPR

    # MIDI Input calculation: 4096 (Base MIDI) + (63 (All Devices) * 32) + 0 (All Channels) = 6112
    MIDI_ALL_INPUTS = 6112

    # =====================================================================
    # METHOD 1: The Input FX Method (From video timestamp 0:33)
    # =====================================================================
    track_idx_1 = RPR.RPR_CountTracks(0)
    RPR.RPR_InsertTrackAtIndex(track_idx_1, True)
    track_1 = RPR.RPR_GetTrack(0, track_idx_1)
    RPR.RPR_GetSetMediaTrackInfo_String(track_1, "P_NAME", "1. Input FX Gen (Rec Input)", True)

    # 1. Add Generative MIDI plugin to the INPUT FX chain (recFX = True)
    RPR.RPR_TrackFX_AddByName(track_1, "JS: MIDI Arpeggiator", True, -1)
    
    # 2. Add Instrument to the STANDARD FX chain (recFX = False)
    RPR.RPR_TrackFX_AddByName(track_1, "VSTi: ReaSynth", False, -1)

    # 3. Setup Recording: Arm track, Set Input to MIDI All, Set Mode to Record Input (0)
    RPR.RPR_SetMediaTrackInfo_Value(track_1, "I_RECARM", 1)
    RPR.RPR_SetMediaTrackInfo_Value(track_1, "I_RECINPUT", MIDI_ALL_INPUTS)
    RPR.RPR_SetMediaTrackInfo_Value(track_1, "I_RECMODE", 0) 


    # =====================================================================
    # METHOD 2: The Record Output Method (From video timestamp 1:13)
    # =====================================================================
    track_idx_2 = RPR.RPR_CountTracks(0)
    RPR.RPR_InsertTrackAtIndex(track_idx_2, True)
    track_2 = RPR.RPR_GetTrack(0, track_idx_2)
    RPR.RPR_GetSetMediaTrackInfo_String(track_2, "P_NAME", "2. Main FX Gen (Rec Output MIDI)", True)

    # 1. Add Generative MIDI plugin to the STANDARD FX chain (recFX = False)
    RPR.RPR_TrackFX_AddByName(track_2, "JS: MIDI Chords", False, -1)
    
    # 2. Add Instrument AFTER the MIDI generator in the STANDARD FX chain
    RPR.RPR_TrackFX_AddByName(track_2, "VSTi: ReaSynth", False, -1)

    # 3. Setup Recording: Arm track, Set Input to MIDI All, Set Mode to Record Output MIDI (4)
    RPR.RPR_SetMediaTrackInfo_Value(track_2, "I_RECARM", 1)
    RPR.RPR_SetMediaTrackInfo_Value(track_2, "I_RECINPUT", MIDI_ALL_INPUTS)
    RPR.RPR_SetMediaTrackInfo_Value(track_2, "I_RECMODE", 4)

    return "Created 2 tracking templates for generative MIDI capture (Input FX routing vs Record Output MIDI routing)."
