def create_object(
    scene_name: str = "Scene",
    object_name: str = "HardSurfacePanel",
    location: tuple = (0, 0, 0),
    scale: float = 1.0,
    material_color: tuple = (0.1, 0.1, 0.1),
    **kwargs,
) -> str:
    """
    Create a Hard Surface panel with a perfectly routed quad-hole using SubD Crease workflow.
    
    Args:
        scene_name: Name of the target scene.
        object_name: Name for the created object.
        location: (x, y, z) world-space position.
        scale: Uniform scale factor (1.0 = default size).
        material_color: (R, G, B) base color in 0-1 range.
        **kwargs: Additional overrides.
        
    Returns:
        Status string.
    """
    import bpy
    import bmesh
    import math
    from mathutils import Vector

    scene = bpy.data.scenes.get(scene_name) or bpy.data.scenes[0]

    # === Step 1: Create Custom All-Quad BMesh ===
    mesh = bpy.data.meshes.new(object_name + "_Mesh")
    obj = bpy.data.objects.new(object_name, mesh)
    scene.collection.objects.link(obj)
    
    bm = bmesh.new()
    
    # 1a. Outer square boundary (8 verts)
    V = []
    outer_coords = [(-1,-1), (0,-1), (1,-1), (1,0), (1,1), (0,1), (-1,1), (-1,0)]
    for x, y in outer_coords:
        V.append(bm.verts.new((x, y, 0)))
        
    # 1b. Inner circular hole (8 verts)
    U = []
    r = 0.4
    angles = [225, 270, 315, 0, 45, 90, 135, 180]
    for a in angles:
        rad = math.radians(a)
        U.append(bm.verts.new((math.cos(rad)*r, math.sin(rad)*r, 0)))
        
    # 1c. Create faces connecting outer boundary to inner hole
    for i in range(8):
        next_i = (i + 1) % 8
        bm.faces.new((V[i], V[next_i], U[next_i], U[i]))
        
    # 1d. Extrude inner hole downwards to create a wall
    W = []
    depth = 0.3
    for a in angles:
        rad = math.radians(a)
        W.append(bm.verts.new((math.cos(rad)*r, math.sin(rad)*r, -depth)))
        
    for i in range(8):
        next_i = (i + 1) % 8
        bm.faces.new((U[i], U[next_i], W[next_i], W[i]))
        
    # 1e. Cap the bottom cleanly using 4 converging quads (Grid Fill logic)
    C_c = bm.verts.new((0, 0, -depth)) # Single center vertex
    # Connect matching opposing segments
    bm.faces.new((C_c, W[1], W[0], W[7]))
    bm.faces.new((C_c, W[3], W[2], W[1]))
    bm.faces.new((C_c, W[5], W[4], W[3]))
    bm.faces.new((C_c, W[7], W[6], W[5]))
    
    bmesh.ops.recalc_normals(bm, faces=bm.faces)

    # === Step 2: Apply Edge Creases ===
    crease_layer = bm.edges.layers.crease.verify()
    top_loop_verts = set(U)
    bot_loop_verts = set(W)
    
    for edge in bm.edges:
        v0, v1 = edge.verts
        # Crease if both vertices belong to the top loop, OR both belong to the bottom loop
        if (v0 in top_loop_verts and v1 in top_loop_verts) or (v0 in bot_loop_verts and v1 in bot_loop_verts):
            edge[crease_layer] = 1.0

    bm.to_mesh(mesh)
    bm.free()
    
    # Enable smooth shading for all polygons
    for p in mesh.polygons:
        p.use_smooth = True

    # === Step 3: Modifiers Workflow ===
    # A. SimpleDeform (to prove the topology holds curvature perfectly)
    mod_deform = obj.modifiers.new(name="Bend", type='SIMPLE_DEFORM')
    mod_deform.deform_method = 'BEND'
    mod_deform.angle = math.radians(45)
    
    # B. Subdivision Surface
    mod_subd = obj.modifiers.new(name="Subdivision", type='SUBSURF')
    mod_subd.levels = 3
    mod_subd.render_levels = 3
    
    # C. Bevel (Catches the creased edge generated by the SubD)
    mod_bevel = obj.modifiers.new(name="Bevel", type='BEVEL')
    mod_bevel.segments = 3
    mod_bevel.width = 0.015
    mod_bevel.limit_method = 'ANGLE'
    mod_bevel.angle_limit = math.radians(30)
    mod_bevel.profile = 0.7
    
    # Handle shading settings safely across Blender versions
    try:
        obj.data.use_auto_smooth = True
        obj.data.auto_smooth_angle = math.radians(60)
        mod_bevel.harden_normals = True
    except AttributeError:
        pass # Ignored in Blender 4.1+ where auto smooth is handled natively via mesh format

    # === Step 4: Material & Shading ===
    mat = bpy.data.materials.new(name=object_name + "_Mat")
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs['Base Color'].default_value = (*material_color, 1.0)
        bsdf.inputs['Metallic'].default_value = 0.8
        bsdf.inputs['Roughness'].default_value = 0.25
    obj.data.materials.append(mat)

    # === Step 5: Lighting Setup ===
    light_data = bpy.data.lights.new(name=object_name+"_Highlight", type='AREA')
    light_data.energy = 800
    light_data.shape = 'RECTANGLE'
    light_data.size = 3.0
    light_obj = bpy.data.objects.new(name=object_name+"_LightObj", object_data=light_data)
    scene.collection.objects.link(light_obj)
    
    # Position light to dramatically catch the hard-surface bevel
    light_pos = Vector((location[0] + 2.5, location[1] - 2.5, location[2] + 3.0))
    light_obj.location = light_pos
    direction = Vector(location) - light_pos
    light_obj.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()

    # === Step 6: Final Positioning ===
    obj.location = Vector(location)
    obj.scale = (scale, scale, scale)

    return f"Created '{object_name}' at {location} featuring all-quad SubD topology with edge creases and bevel highlights."
