def create_component(
    output_dir: str,
    title_text: str = "GARY.SIMON",
    body_text: str = "A comprehensive approach to modern UI design.",
    color_scheme: str = "dark",
    accent_color: str = "#00bfff",
    width_px: int = 1200,
    height_px: int = 800,
    **kwargs,
) -> dict:
    """
    Create a web component reproducing the Cascading Staggered Text Reveal visual effect.
    Writes index.html, style.css, and script.js to output_dir.
    """
    import os

    os.makedirs(output_dir, exist_ok=True)

    if color_scheme == "dark":
        bg_color = "#0d111c"
        text_color = "#f0f0f0"
        sub_text_color = "rgba(255, 255, 255, 0.6)"
    else:
        bg_color = "#ffffff"
        text_color = "#1a1a2e"
        sub_text_color = "rgba(0, 0, 0, 0.6)"

    css = f"""/* Cascading Staggered Text Reveal */
*, *::before, *::after {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

:root {{
    --bg: {bg_color};
    --text: {text_color};
    --sub-text: {sub_text_color};
    --accent: {accent_color};
    --width: {width_px}px;
    --height: {height_px}px;
}}

body {{
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    background: var(--bg);
    color: var(--text);
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
}}

.container {{
    width: var(--width);
    height: var(--height);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 2rem;
    
    /* Prevent FOUC (Flash of Unstyled Content) before JS runs */
    opacity: 0; 
    visibility: hidden;
}}

.title {{
    font-family: 'Bebas Neue', sans-serif;
    font-size: clamp(4rem, 10vw, 8rem);
    text-transform: uppercase;
    text-align: center;
    line-height: 1.05; /* Tight bounding box for precise masking */
    margin-bottom: 1rem;
    letter-spacing: 2px;
}}

.body-text {{
    font-size: 1.25rem;
    color: var(--sub-text);
    text-align: center;
    max-width: 600px;
    line-height: 1.5;
}}

/* 
  CORE PATTERN: 
  The .line elements generated by SplitType act as the mask.
  We apply clip-path to crop anything that steps outside the line's bounding box.
*/
.title .line, .body-text .line {{
    clip-path: polygon(0 0, 100% 0, 100% 100%, 0 100%);
}}

/* Ensure the accent color highlights punctuation or specific spans if needed */
.accent {{
    color: var(--accent);
}}
"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cascading Text Reveal</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <h1 class="title">{title_text}</h1>
        <p class="body-text">{body_text}</p>
    </div>

    <!-- External Libraries -->
    <script src="https://unpkg.com/split-type"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>
    <script src="script.js"></script>
</body>
</html>"""

    js = f"""// Cascading Staggered Text Reveal Logic
document.addEventListener('DOMContentLoaded', () => {{
    
    // 1. Parse the DOM text into accessible wrapper spans
    const titleSplit = new SplitType('.title', {{ types: 'lines, words, chars' }});
    const bodySplit = new SplitType('.body-text', {{ types: 'lines, words' }});

    // 2. Reveal the container now that the DOM is split and ready
    // This prevents the user from seeing the unformatted text before animation
    gsap.set('.container', {{ autoAlpha: 1 }});

    // 3. Construct the Master Timeline
    const tl = gsap.timeline();

    // 4. Animate the Title Characters
    // We animate 'y' from 115% (pushed entirely below the clipped line mask) to 0%
    tl.fromTo(titleSplit.chars, 
        {{ 
            y: "115%" 
        }},
        {{
            y: "0%",
            stagger: 0.04,         // The cascade delay between each letter
            duration: 0.6,
            ease: "power3.out",    // Snappy decelleration
            delay: 0.2             // Initial pause before animation starts
        }}
    );

    // 5. Animate the Body Text Words (Sub-animation for complete feel)
    // Similar masked reveal, but staggering whole words instead of characters
    tl.fromTo(bodySplit.words,
        {{ 
            y: "115%" 
        }},
        {{
            y: "0%",
            stagger: 0.02,
            duration: 0.5,
            ease: "power2.out"
        }},
        "-=0.4" // Overlap with the title animation slightly for fluidity
    );
}});
"""

    files = []
    for fname, content in [("index.html", html), ("style.css", css), ("script.js", js)]:
        path = os.path.join(output_dir, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        files.append(path)

    return {
        "html": html,
        "css": css,
        "js": js,
        "files": files,
    }
