def create_slide(
    output_pptx_path: str,
    title_text: str = "柱 型 圖\n座標軸選項 (範圍最大值最小值)",
    **kwargs,
) -> str:
    """
    Create a PPTX file reproducing the 'Negative Space Axis Hacking' visual effect.
    """
    from pptx import Presentation
    from pptx.chart.data import CategoryChartData
    from pptx.enum.chart import XL_CHART_TYPE, XL_TICK_LABEL_POSITION
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.shapes import MSO_SHAPE
    from pptx.enum.text import PP_ALIGN
    from PIL import Image
    import urllib.request
    import os

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    slide = prs.slides.add_slide(prs.slide_layouts[6]) # Blank layout

    # === Layer 1: Background composited via PIL ===
    bg_color = (60, 50, 110)
    bg_img = Image.new("RGBA", (1920, 1080), bg_color)
    try:
        # Download fitness-themed background photo
        req = urllib.request.Request(
            "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80",
            headers={'User-Agent': 'Mozilla/5.0'}
        )
        with urllib.request.urlopen(req) as response:
            photo = Image.open(response).convert("RGBA").resize((1920, 1080))
            # Apply heavy dark purple overlay for text contrast
            overlay = Image.new("RGBA", (1920, 1080), (60, 50, 110, 215))
            bg_img = Image.alpha_composite(photo, overlay)
    except Exception as e:
        print(f"Background download failed, using solid fallback: {e}")
    
    bg_path = "temp_bg_layer.png"
    bg_img.save(bg_path)
    slide.shapes.add_picture(bg_path, 0, 0, prs.slide_width, prs.slide_height)
    if os.path.exists(bg_path):
        os.remove(bg_path)

    # === Layer 2: Typography ===
    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(6), Inches(1.5))
    tf = title_box.text_frame
    p = tf.paragraphs[0]
    p.text = title_text
    p.font.size = Pt(28)
    p.font.color.rgb = RGBColor(255, 255, 255)
    p.font.bold = True

    # === Layer 3: Native Chart with Axis Hacking ===
    chart_data = CategoryChartData()
    categories = ['Running', 'Cycling', 'Dancing', 'Yoga', 'Weights', 'Sports', 'Stretch']
    chart_data.categories = categories
    # Add Data
    chart_data.add_series('Male', (0.45, 0.62, 0.37, 0.28, 0.66, 0.78, 0.34))
    chart_data.add_series('Female', (0.55, 0.38, 0.63, 0.72, 0.34, 0.22, 0.66))

    x, y, cx, cy = Inches(1.5), Inches(1.5), Inches(10.33), Inches(5.0)
    chart = slide.shapes.add_chart(
        XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data
    ).chart

    # Global chart text styling
    chart.font.size = Pt(12)
    chart.font.color.rgb = RGBColor(255, 255, 255)

    # Format bars
    chart.plots[0].overlap = 20
    chart.plots[0].gap_width = 120
    chart.series[0].format.fill.solid()
    chart.series[0].format.fill.fore_color.rgb = RGBColor(255, 50, 100) # Neon Pink
    chart.series[1].format.fill.solid()
    chart.series[1].format.fill.fore_color.rgb = RGBColor(20, 15, 35)   # Deep Black/Violet

    # THE CORE SKILL: Hacking the axis bounds to create negative layout space
    val_axis = chart.value_axis
    val_axis.minimum_scale = -0.2   # Creates a 20% empty void at the bottom
    val_axis.maximum_scale = 0.8
    val_axis.major_unit = 0.1
    val_axis.has_major_gridlines = False

    # Hide default X-axis text, as we will use a data table instead
    cat_axis = chart.category_axis
    cat_axis.tick_label_position = XL_TICK_LABEL_POSITION.NONE
    cat_axis.has_major_gridlines = False

    # Append data table below the space
    chart.has_data_table = True
    chart.data_table.show_legend_keys = True

    # === Layer 4: Masking Block ===
    # Covers the unintended negative axis labels (-10%, -20%) generated by the hack
    mask = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(0.8), y + cy - Inches(1.8), Inches(0.6), Inches(0.9)
    )
    mask.fill.solid()
    mask.fill.fore_color.rgb = RGBColor(60, 50, 110) # Matches background overlay
    mask.line.fill.background()

    # === Layer 5: Emojis in Negative Space ===
    emojis = ["🏃", "🚴", "💃", "🧘", "🏋️", "⚽", "🤸"]
    # Calculate geometric distribution relative to chart dimensions
    start_x = x + Inches(0.6) 
    usable_width = cx - Inches(0.8)
    step = usable_width / len(emojis)

    for i, emoji in enumerate(emojis):
        bx = start_x + (i * step) + (step / 2) - Inches(0.25)
        by = y + cy - Inches(1.6) # Position precisely in the negative void, above the data table
        
        tb = slide.shapes.add_textbox(bx, by, Inches(0.5), Inches(0.5))
        tb.text_frame.word_wrap = False
        p = tb.text_frame.paragraphs[0]
        p.text = emoji
        p.font.size = Pt(28)
        p.alignment = PP_ALIGN.CENTER

    prs.save(output_pptx_path)
    return output_pptx_path
