def create_object(
    scene_name: str = "Scene",
    object_name: str = "BoxProjectedAsset",
    location: tuple = (0, 0, 0),
    scale: float = 1.0,
    material_color: tuple = (0.8, 0.8, 0.8),
    **kwargs,
) -> str:
    """
    Create a complex multi-tiered cylinder demonstrating UV-less Box Projection.

    Args:
        scene_name: Name of the target scene.
        object_name: Name for the created object.
        location: (x, y, z) world-space position.
        scale: Uniform scale factor.
        material_color: Base tint for the material (not highly visible due to texture).
        **kwargs: 
            blend_amount (float): The amount to blur the seams of the box projection (default: 0.2).

    Returns:
        Status string.
    """
    import bpy
    import bmesh
    from mathutils import Vector

    scene = bpy.data.scenes.get(scene_name) or bpy.data.scenes[0]
    blend_amount = kwargs.get("blend_amount", 0.2)

    # === Step 1: Create Base Geometry ===
    mesh = bpy.data.meshes.new(object_name + "_Mesh")
    obj = bpy.data.objects.new(object_name, mesh)
    scene.collection.objects.link(obj)

    bm = bmesh.new()
    # Base cylinder
    bmesh.ops.create_cone(
        bm, cap_ends=True, cap_tris=False, segments=32, 
        radius1=1.0, radius2=1.0, depth=0.5
    )

    # Find the top cap face
    top_face = next(f for f in bm.faces if f.normal.z > 0.9)

    # First Inset (Scale vertices of a zero-distance extrusion)
    ret = bmesh.ops.extrude_discrete_faces(bm, faces=[top_face])
    top_face = ret['faces'][0]
    center = top_face.calc_center_bounds()
    for v in top_face.verts:
        v.co.x = center.x + (v.co.x - center.x) * 0.6
        v.co.y = center.y + (v.co.y - center.y) * 0.6

    # Extrude up
    ret = bmesh.ops.extrude_discrete_faces(bm, faces=[top_face])
    top_face = ret['faces'][0]
    bmesh.ops.translate(bm, vec=(0, 0, 0.4), verts=top_face.verts)

    # Second Inset (Indent for the hole)
    ret = bmesh.ops.extrude_discrete_faces(bm, faces=[top_face])
    top_face = ret['faces'][0]
    center = top_face.calc_center_bounds()
    for v in top_face.verts:
        v.co.x = center.x + (v.co.x - center.x) * 0.5
        v.co.y = center.y + (v.co.y - center.y) * 0.5

    # Extrude down into the mesh
    ret = bmesh.ops.extrude_discrete_faces(bm, faces=[top_face])
    top_face = ret['faces'][0]
    bmesh.ops.translate(bm, vec=(0, 0, -0.3), verts=top_face.verts)

    bm.to_mesh(mesh)
    bm.free()

    # Shade smooth
    for poly in mesh.polygons:
        poly.use_smooth = True

    # === Step 2: Modifiers ===
    # Bevel to catch sharp edges generated by bmesh
    bevel = obj.modifiers.new(name="Bevel", type='BEVEL')
    bevel.limit_method = 'ANGLE'
    bevel.angle_limit = 0.5  # ~28.6 degrees
    bevel.width = 0.03
    bevel.segments = 3

    # Subdiv to smooth the cylindrical walls
    subdiv = obj.modifiers.new(name="Subdivision", type='SUBSURF')
    subdiv.levels = 2
    subdiv.render_levels = 2

    # === Step 3: Build Material with Box Projection ===
    mat = bpy.data.materials.new(name=object_name + "_Mat")
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    output = nodes.new('ShaderNodeOutputMaterial')
    output.location = (800, 0)

    principled = nodes.new('ShaderNodeBsdfPrincipled')
    principled.location = (500, 0)
    principled.inputs['Metallic'].default_value = 0.4
    principled.inputs['Roughness'].default_value = 0.3

    # Generate a native Blender grid image to prove projection works
    img_name = "Generated_Color_Grid"
    img = bpy.data.images.get(img_name)
    if not img:
        img = bpy.data.images.new(name=img_name, width=1024, height=1024, alpha=False)
        img.generated_type = 'COLOR_GRID'

    # The Core Technique: Image Texture set to BOX projection
    tex_img = nodes.new('ShaderNodeTexImage')
    tex_img.location = (200, 0)
    tex_img.image = img
    tex_img.projection = 'BOX'
    tex_img.projection_blend = blend_amount

    mapping = nodes.new('ShaderNodeMapping')
    mapping.location = (0, 0)
    mapping.inputs['Scale'].default_value = (2.0, 2.0, 2.0)

    # Use Object Coordinates instead of UVs
    tex_coord = nodes.new('ShaderNodeTexCoord')
    tex_coord.location = (-200, 0)

    # Connect Graph
    links.new(tex_coord.outputs['Object'], mapping.inputs['Vector'])
    links.new(mapping.outputs['Vector'], tex_img.inputs['Vector'])
    links.new(tex_img.outputs['Color'], principled.inputs['Base Color'])
    links.new(principled.outputs['BSDF'], output.inputs['Surface'])

    obj.data.materials.append(mat)

    # === Step 4: Position & Scale ===
    obj.location = Vector(location)
    obj.scale = (scale, scale, scale)

    return f"Created '{object_name}' with UV-less Box Projection texturing (Blend: {blend_amount})"
